MPAS-Dev/compass

clean_testcase.py, manage_regression_suite.py, setup_testcase.py
This branch contains the full history of https://github.com/MPAS-Dev/MPAS-Model/tree/develop/testing_and_setup/compass
=> Merge COMPASS contents  from MPAS-Dev/MPAS-Model/develop

recipe/LICENSE, recipe/build_and_upload.bash, recipe/conda_build_config.yaml, recipe/create_new_compass_env.bash, recipe/meta.yaml
This is from https://github.com/MPAS-Dev/MPAS-Tools/tree/master/compass
=> Add the recipe for the compass conda metapackage

azure-pipelines.yml
There were still paths from MPAS-Model
=> Fix path in Azure CI

ocean/global_ocean/EC15to60/build_mesh/config_base_mesh.xml, ocean/global_ocean/config_files/config_base_mesh.xml
These links only belong in EC15to60
closes #19
=> Remove links to geojsons from shared base_mesh

.gitignore
The most important ones are the python cache files, which we definitely don't want to be adding.
=> Add a lot more to .gitignore

recipe/meta.yaml
Update `geometric_features` and `mpas_tools` versions and add `lxml`, `matplotlib` and `cmocean` as dependencies.
=> Update metapackage to 0.1.12

deploy/create_compass_env.py
To run it, you need to start with an environment with the `requests` and `progressbar2` packages (which could be a previous
`compass` environment, `e3sm-unified` or a temporary environment the user creates just for this installation.
This script is based on the one used in e3sm-unified: 
https://github.com/E3SM-Project/e3sm-unified/blob/master/e3sm_supported_machines/create_new_e3sm_unified_env.py
=> Add deployment script for compass envs

load_compass_env.sh, setup_testcase.py
This merge also modifies the setup script to link to this new location if requested.
=> Move load_compass_env.sh to the base dir

docs/machine_specific_instructions/lanl.rst, docs/machine_specific_instructions/nersc.rst
Small changes to documentation.
=> Small changes to compile instructions. Note on Intel 19 & PIO2.

ocean/global_ocean/scripts/create_E3SM_coupling_files.py
...if there are ice-shelf cavities
Fixes #44
=> Add landIceMask to sea ice IC

ocean/gotm/2.5km/default/config_analysis.xml, ocean/gotm/2.5km/default/config_driver.xml, ocean/gotm/2.5km/default/config_forward.xml, ocean/gotm/2.5km/default/config_init.xml, ocean/gotm/2.5km/default/gotmturb.nml, ocean/gotm/2.5km/default/plot_profile.py
This PR is a copy of https://github.com/MPAS-Dev/compass/pull/66 which fixes the issues raised there.
closes #66
=> Add GOTM test

load_compass_env.sh
=> Update compass version lin load_compass_env.sh

compass/list.py
It's annoying to have them in random order.
=> Alphabetize suites when listing them

compass/validate.py
This has helped a lot with suites, and would make it much easier to tell success from failure when validating individual test cases.
=> Add color to validation

.gitignore, .gitmodules, compass/landice/landice.cfg, compass/ocean/ocean.cfg, docs/developers_guide/command_line.rst, docs/developers_guide/landice/index.rst, docs/developers_guide/ocean/index.rst, docs/developers_guide/organization.rst, docs/developers_guide/overview.rst, docs/developers_guide/quick_start.rst, docs/index.rst, docs/users_guide/config_files.rst, docs/users_guide/landice/index.rst, docs/users_guide/machines/osx.rst, docs/users_guide/quick_start.rst
Remove `MPAS-Model` submodules.
Change references to `MPAS-Model` repo --> `E3SM-Project` and `MALI-Dev` both the code and the documentation.
=> Add E3SM-Project and MALI-Dev submodules

.gitmodules, docs/index.rst, docs/machine_specific_instructions/anvil.rst, docs/machine_specific_instructions/lanl.rst, docs/machine_specific_instructions/linux.rst, docs/machine_specific_instructions/nersc.rst, docs/machine_specific_instructions/osx.rst, docs/ocean/introduction.rst, docs/ocean/test_cases/isomip_plus_at_lanl.rst, docs/users_guide/overview.rst
Update legacy docs with E3SM move
=> Add E3SM submodule, remove MPAS-Model submodules

conda/compass_env/spec-file-mpich.txt, conda/compass_env/spec-file-nompi.txt, conda/compass_env/spec-file-openmpi.txt
This is helpful for folks that want to use it directly for linting or want to use the vim plugin.
=> Add flake8 to development environments

conda/compass_env/spec-file-mpich.txt, conda/compass_env/spec-file-openmpi.txt
I ran into errors on my new Linux laptop because `make` was not available.
=> Add make to dev environments

docs/developers_guide/overview.rst
Update the docs with info about flake8 being added to the conda env.
=> Provide flake8 info in Developer's Guide

compass/model.py, compass/namelist.py, compass/ocean/iceshelf.py, compass/ocean/tests/global_convergence/cosine_bell/forward.py, compass/step.py, docs/developers_guide/api.rst, docs/developers_guide/docs.rst, docs/developers_guide/framework.rst, docs/developers_guide/organization.rst
These are more intuitive if they're methods of Step instead. This merge also updates the test cases and core framework that is affected.  It also updates the documentation with these changes.
=> Move `namelist.update` and `model.update_namelist_pio` into `Step`

example_configs/landice.cfg, example_configs/ocean.cfg
I noticed these are out of date when working with @altheaden today.
=> Update example config files

compass/landice/tests/greenland/albany_input.yaml, compass/landice/tests/greenland/albany_schoof_input.yaml, compass/landice/tests/greenland/run_model.py
When I ported the test cases in the previous branch, I had inadvertently
used the Albany yaml file from the dome test case.
=> Add Albany yaml files specific to Greenland configuration

compass/ocean/vertical/__init__.py, compass/ocean/vertical/zlevel.py, compass/ocean/vertical/zstar.py, docs/developers_guide/organization.rst
These were mostly missed in #118
=> Some fixes to docstrings and documentation

.gitignore, conda/configure_compass_env.py
This should speed up creating the development environment a bit
=> Switch dev environment creation to use mamba

ocean/mixed_layer_eddy/0.6km/double_front/config_driver.xml, ocean/mixed_layer_eddy/0.6km/double_front/config_forward.xml, ocean/mixed_layer_eddy/0.6km/double_front/config_init.xml, ocean/mixed_layer_eddy/0.6km/single_front/config_driver.xml, ocean/mixed_layer_eddy/0.6km/single_front/config_forward.xml, ocean/mixed_layer_eddy/0.6km/single_front/config_init.xml
This PR adds the configuration files for two mixed layer eddy test cases as described in https://github.com/MPAS-Dev/MPAS-Model/pull/855.
=> Mixed layer eddy test cases

docs/developers_guide/framework.rst
Some spelling and grammar typos in framework fixed.
=> Fix Dev Guide typos

docs/developers_guide/framework.rst, docs/developers_guide/troubleshooting.rst, docs/index.rst
This will be an area for collecting common issues that developers run into and their likely solutions.
=> Add a troubleshooting section to the developer's guide

docs/developers_guide/troubleshooting.rst
These are likely to happen to many new users of LANL Macs.
=> Add troubleshooting proxy issues on LANL Macs

docs/developers_guide/quick_start.rst
Quick Start needed info about config files and some misc typos fixed.
=> Update Quick Start for Developers

docs/developers_guide/quick_start.rst
This should hopefully give more clarity.
=> Divide the conda quick-start into sections

docs/developers_guide/quick_start.rst
Reorganization to add "Optional flags" section, remove some redundancy, and take unrelated text out of "Troubleshooting".
=> Additional improvements to developer's quick start

conda/configure_compass_env.py
We want to be compatible with earlier versions of python in this particular script.
=> Remove f-strings in config script

compass/io.py
This will help users find the file if they want to.
This merge also includes some cleanup like switching to f-strings and removing camel-case variable names.
=> Add destination path to download stdout

compass/validate.py
When errors occur during variable validation such as a mis-match in the number of cells, print an error and mark the test as failing but don't raise an exception.  This way, the errors will appear in the log and the test will be marked as failing but there will not be a stack trace, nor will the suite output show that the test execution (rather than baseline validation) failed.
closes #242
=> Print but don't raise errors in validation

compass/landice/tests/circular_shelf/decomposition_test/__init__.py
Increased threshold slightly to allow test to pass
=> Threshold Levels for circularshelf_decompostion_test

compass/clean.py, compass/setup.py
Fixing some typos and incorrect docstrings.
=> Clean-up pull request

compass/landice/tests/greenland/run_model.py
updating to file name url=‘https://web.lcrc.anl.gov/public/e3sm/inputdata/glc/mpasli/mpas.gis20km/gis_20km_r01.20210824.nc’
=> updating 20 km greenland file to new version

compass/ocean/tests/global_ocean/files_for_e3sm/seaice_initial_condition.py
The files are placed in `...ice/mpas-seaice` whereas they were previously in `...ocn/mpas-seaice`.
=> Fix location for mpas-seaice initial condition

azure-pipelines.yml, ci/generate.py, ci/mpi_mpich.yaml, ci/mpi_mpich_python3.10.yaml, ci/mpi_mpich_python3.7.yaml, ci/mpi_mpich_python3.8.yaml, ci/mpi_mpich_python3.9.yaml, ci/mpi_nompi.yaml, ci/mpi_nompi_python3.10.yaml, ci/mpi_nompi_python3.7.yaml, ci/mpi_nompi_python3.8.yaml, ci/mpi_nompi_python3.9.yaml, ci/mpi_openmpi.yaml, ci/mpi_openmpi_python3.10.yaml, ci/mpi_openmpi_python3.7.yaml, ci/mpi_openmpi_python3.8.yaml, ci/mpi_openmpi_python3.9.yaml, ci/template.yaml, conda/compass_env/spec-file.template, conda/recipe/meta.yaml, setup.py
A recent update to pyamg fixes issues with the latest scipy.
=> Constrain pyamg (instead of scipy)

conda/compass_env/spec-file.template, conda/recipe/meta.yaml
This brings in https://github.com/MPAS-Dev/MPAS-Tools/pull/452
=> Update mpas_tools to v0.13.0

compass/ocean/tests/global_ocean/init/initial_state.py
The `mesh` parameter was missing
=> Fix `initial_state` docstring in `global_ocean`

compass/logging.py, compass/run.py, compass/testcase.py, docs/developers_guide/api.rst
This should make it easier to find the code that was run in each test case.
=> Add logging of calls to run() and validate() methods

compass/default.cfg, conda/bootstrap.py, conda/compass_env/build.template, conda/compass_env/spec-file.template, conda/configure_compass_env.py, conda/default.cfg, conda/recipe/meta.yaml, conda/shared.py
Move the config options related to deployment of the conda env. to the conda directory.
Make sure the shared environment gets updated and mamba/boa installed.
=> Add support for compass test release

conda/compass_env/spec-file.template, conda/configure_compass_env.py, conda/recipe/meta.yaml
This version adds a missing environment variable needed on Compy
=> Update to mache>=1.3.2

docs/developers_guide/landice/api.rst, docs/developers_guide/landice/test_groups/kangerlussuaq.rst, docs/developers_guide/landice/test_groups/koge_bugt_s.rst, docs/users_guide/landice/test_groups/kangerlussuaq.rst, docs/users_guide/landice/test_groups/koge_bugt_s.rst, docs/users_guide/quick_start.rst
Some API fixes, some title fixes, some formatting of code blocks.
=> Many fixes to the documentation

conda/compass_env/spec-file.template
These are handy for checking CF compliance of MPAS output.
=> Add cfchecker and udunits2 to conda environment

compass/run/serial.py
Default value for default is already None
=> Remove redundant default argument values

conda/shared.py
See https://github.com/mamba-org/mamba/issues/1708
=> Constrain mamba to avoid recent issue

compass/version.py, conda/recipe/meta.yaml, docs/versions.rst
Deployment:
- Base:
- With LAPACK and PETSc:
- With Albany:
=> Update to v1.1.0

compass/parallel.py
This is causing compass to hang in interactive jobs
=> Remove `--exclusive` flag from slurm steps

utils/matrix/setup_matrix.py
Something I thought of only right after merging #438
=> Fix job script name in matrix utility

compass/ocean/suites/wetdry.txt
This adds a suite containing all wetting and drying test cases.
=> Add wetdry suite

conda/bootstrap.py, conda/configure_compass_env.py, conda/shared.py
This should make a fresh deployment a little faster.
=> Switch to mambaforge and add mamba init

utils/e3sm_update/README.md, utils/e3sm_update/example.cfg, utils/e3sm_update/test_e3sm_changes.py
Currently, this is designed with the E3SM-Project submodule in mind but with generalization to other submodules hopefully possible with relative ease.
=> Add a utility for testing updates to E3SM submodule

compass/machines/anvil.cfg, compass/machines/compy.cfg, compass/version.py, conda/bootstrap.py, conda/compass_env/spec-file.template, conda/configure_compass_env.py, conda/petsc_supported.txt, conda/recipe/meta.yaml, docs/developers_guide/machines/anvil.rst, docs/developers_guide/machines/chrysalis.rst, docs/developers_guide/machines/index.rst, docs/users_guide/machines/anvil.rst, docs/users_guide/machines/chrysalis.rst
=> Update to 1.2.0-alpha.3 with mache 1.9.0

.github/pull_request_template.md
=> Add a template for PRs with a checklist

conda/pnetcdf/ci/linux_mpi_mpich.yaml, conda/pnetcdf/ci/linux_mpi_openmpi.yaml, conda/pnetcdf/ci/osx_mpi_mpich.yaml, conda/pnetcdf/ci/osx_mpi_openmpi.yaml, conda/pnetcdf/recipe/meta.yaml, conda/scorpio/ci/linux_mpi_mpich.yaml, conda/scorpio/ci/linux_mpi_openmpi.yaml, conda/scorpio/ci/osx_mpi_mpich.yaml, conda/scorpio/ci/osx_mpi_openmpi.yaml, conda/scorpio/recipe/meta.yaml
This is needed to handle an impending update to MPAS-Tools
=> Update hdf5 in pnetcdf and scorpio packages to match conda-forge

README.md, azure-pipelines.yml, docs/design_docs/compass_package.rst, docs/developers_guide/docs.rst, docs/developers_guide/ocean/index.rst, docs/developers_guide/overview.rst, docs/developers_guide/quick_start.rst, docs/developers_guide/troubleshooting.rst, docs/tutorials/dev_add_param_study.rst, docs/tutorials/dev_add_test_group.rst, docs/tutorials/dev_porting_legacy.rst, docs/users_guide/config_files.rst, docs/users_guide/quick_start.rst, docs/versions.rst
=> Rename master --> main

conda/bootstrap.py, conda/compass_env/spec-file.template
=> Disable otps on OSX

utils/matrix/README.md
=> Fix docs for matrix utility

azure-pipelines.yml
=> Fix base env update in Azure tests

conda/shared.py
=> Fix deployment using python 2

compass/machines/chicoma-cpu.cfg, conda/albany_supported.txt, conda/petsc_supported.txt, conda/unsupported.txt, docs/developers_guide/machines/chicoma.rst, docs/developers_guide/machines/index.rst, docs/users_guide/machines/chicoma.rst, docs/users_guide/machines/index.rst, docs/users_guide/quick_start.rst, utils/matrix/setup_matrix.py
Checklist
Spack building and testing:
Closes #291
=> Add chicoma-cpu support

docs/developers_guide/quick_start.rst
This merge adds a little additional material in the Developers Guide about not mixing environments when switching between branches.
Checklist
=> Elaborate note on not mixing envs for different branches

compass/ocean/tests/global_convergence/cosine_bell/__init__.py, compass/ocean/tests/global_convergence/cosine_bell/cosine_bell.cfg, compass/ocean/tests/global_convergence/cosine_bell/init.py
This PR moves the generation of an initial state for the ocean global cosine bell test case from init mode to the initial state compass step. 
Checklist
=> Port cosine bell initial state

.github/workflows/build_workflow.yml, .github/workflows/docs_workflow.yml, conda/bootstrap.py, conda/configure_compass_env.py, conda/shared.py
This can help with debugging.
It has been added to github actions because otherwise errors in deployment are very difficult to debug.
Checklist
=> Add `--verbose` flag to deployment script 

conda/bootstrap.py
=> Fix print for petsc in verbose mode

compass/ocean/suites/pr.txt, compass/ocean/suites/wetdry.txt
=> Fix ISOMIP+ test names in suites

.pre-commit-config.yaml, compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py, conda/compass_env/spec-file.template, conda/recipe/meta.yaml
This allows us to use `pyremap`, supplying a parallel executable and running with multiple MPI tasks.
It will also be more adaptable to task parallelism in the future.
This merge updates to `mpas_tools 0.19.0` to bring in functionality needed to support this change.
Checklist
=> Make mapping file for sea-ice partitioning in compass 

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py, compass/ocean/tests/global_ocean/files_for_e3sm/files_for_e3sm_step.py, compass/ocean/tests/global_ocean/files_for_e3sm/ocean_graph_partition.py, compass/ocean/tests/global_ocean/files_for_e3sm/ocean_initial_condition.py, compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py, docs/users_guide/ocean/test_groups/global_ocean.rst
This merge also fixes absolute path for graph files in `files_for_e3sm` for existing meshes.
Checklist
=> Add metadata in `files_for_e3sm` for existing meshes

compass/cache.py
The command was not updated after the move to a single database root for all components
Checklist
=> Fix `compass cache`

compass/landice/tests/circular_shelf/albany_input.yaml
=> Add missing newline

docs/developers_guide/quick_start.rst
Update to docs to add details on how conda environments are used when switching between compass branches.
Checklist
=> Update guidance on switching between branches

compass/ocean/tests/ice_shelf_2d/__init__.py, compass/ocean/tests/ice_shelf_2d/default/__init__.py, compass/ocean/tests/ice_shelf_2d/initial_state.py, compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py, compass/ocean/tests/ice_shelf_2d/ssh_adjustment.py, compass/ocean/tests/ice_shelf_2d/viz.py, compass/ocean/tests/isomip_plus/evap.py, compass/ocean/tests/isomip_plus/process_geom.py, compass/ocean/tests/isomip_plus/viz/__init__.py
I'm just keeping linting of ice-shelf tests separate from other unrelated work, e.g. #512 
Checklist
=> Lint ice shelf tests

compass/setup.py
It is often convenient to run steps on their own, so it will be convenient to have a job script (and a link to the load script) for each step.
Checklist
=> Add job script to steps

compass/ocean/tests/global_ocean/global_ocean.cfg, compass/ocean/tests/global_ocean/mesh/arrm10to60/arrm10to60.cfg, compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg, compass/ocean/tests/global_ocean/mesh/kuroshio/kuroshio.cfg, compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg, compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg, compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg, compass/ocean/tests/global_ocean/metadata.py
This is in anticipation of having "official" versions of these meshes soon.
Checklist
=> Bump all the meshes to E3SM v3, revision 1

compass/ocean/cached_files.json
These need updating following #610 
Checklist
=> Update global ocean init cache files

utils/e3sm_update/test_e3sm_changes.py
This merge updates the E3SM-Project submodule from [20784fb](https://github.com/E3SM-Project/E3SM/tree/20784fb) to [de075c7](https://github.com/E3SM-Project/E3SM/tree/de075c7).
This update includes the following MPAS-Ocean and MPAS-Frameworks PRs (check mark indicates bit-for-bit with previous PR in the list):
Checklist
closes #500
closes #497
=> Update e3sm project

compass/ocean/suites/wetdry.txt, compass/ocean/tests/dam_break/__init__.py, compass/ocean/tests/dam_break/forward.py, compass/ocean/tests/dam_break/namelist.ramp.forward, compass/ocean/tests/dam_break/ramp/__init__.py, compass/ocean/tests/drying_slope/__init__.py, compass/ocean/tests/drying_slope/forward.py, compass/ocean/tests/drying_slope/ramp/__init__.py, compass/ocean/tests/drying_slope/streams.forward, docs/developers_guide/ocean/test_groups/dam_break.rst, docs/developers_guide/ocean/test_groups/drying_slope.rst, docs/users_guide/ocean/test_groups/dam_break.rst, docs/users_guide/ocean/test_groups/drying_slope.rst
This PR is for testing the wetting-and-drying ramp feature introduced in https://github.com/E3SM-Project/E3SM/pull/5590
Checklist
=> Add ocean wetting-and-drying ramp tests

compass/ocean/tests/global_ocean/files_for_e3sm/graph_partition.py
This is needed for Sunspot, see: https://github.com/E3SM-Project/E3SM/pull/5611#issuecomment-1583072093
=> Add partition files for 52-core nodes

compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
=> Don't run remap_ice_shelf_melt without ice-shelf cavities

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py, compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py, docs/developers_guide/ocean/api.rst, docs/developers_guide/ocean/test_groups/global_ocean.rst
This is used in E3SM runs with data atmospheric forcing.
Checklist
=> Add a step for remapping sea surface salinity restoring

compass/ocean/cached_files.json
This is why I need to *always* run the `pr` suite...
I missed these cache files in #679 
Checklist
=> Add missing data ice-shelf melt cache files

compass/ocean/suites/ecwisc30to60.txt, compass/ocean/suites/quwisc240.txt, compass/ocean/suites/quwisc240_for_e3sm.txt, compass/ocean/suites/sowisc12to60.txt, compass/ocean/suites/wcwisc14.txt
=> Remove `data_ice_shelf_melt` tests from suites

compass/ocean/mesh/remap_topography.cfg, compass/ocean/tests/global_ocean/mesh/__init__.py, compass/ocean/tests/utility/extrap_woa/extrap_woa.cfg, docs/developers_guide/organization.rst, docs/users_guide/ocean/framework/mesh.rst
This version uses ice surface elevation, rather than bedrock below ice in Greenland.
Checklist
=> Update to GEBCO 2023 topography

compass/ocean/tests/global_ocean/performance_test/__init__.py
Needs https://github.com/E3SM-Project/E3SM/pull/5910
Checklist
Fixes #693
=> Update variables checked in DISMF performance test

compass/ocean/mesh/remap_topography.py, compass/ocean/tests/global_ocean/files_for_e3sm/diagnostic_maps.py, compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py, compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py, compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py, compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py, conda/compass_env/spec-file.template
Another try at #698 
This brings in full support for MPAS vertex meshes, and switches to using SCRIP files for all MPAS meshes (on cells, vertices and edges) for better future support for `mbtempest`.
Checklist
=> Update to `pyremap` v1.1.0 (again)

compass/config.py, conda/compass_env/spec-file.template, conda/recipe/meta.yaml
=> Update to mpas_tools 0.26.0

compass/landice/tests/ismip6_forcing/ocean_thermal/process_thermal_forcing.py
This PR adds the renaming of the ismip6 variable `z_bnds` to the MALI variable `ismip6shelfMelt_zBndsOcean`, which was previously dropped in the `ismip6_forcing` test group & `ocean_thermal` test case. The reason for the change is that the bounds of each ocean layer are needed in the ocean re-extrapolation scheme in MALI.
Along with the main change mentioned above, the PR also includes some clean-up to address PEP8-related errors raised by `pre-commit`. 
Checklist
=> add the variable 'zbnds' for ocean depth

compass/ocean/mesh/remap_topography.cfg, docs/users_guide/ocean/framework/mesh.rst
=> Increase remap tasks

compass/version.py, conda/compass_env/spec-file.template, conda/recipe/meta.yaml
This brings in a new topography smoothing tools before init that skips ice-shelf cavities
The compass version has also been bumped to v1.2.0-alpha.8
Checklist
=> Update to mpas_tools 0.29.0

conda/bootstrap.py, conda/configure_compass_env.py, docs/developers_guide/deploying_spack.rst
This means that we update the release version for new spack envs and we update the alpha, beta, etc. for dependency changes.
The docs for spack deployment have been updated accordingly.
Checklist
=> Use only compass release version is spack env name

.github/workflows/build_workflow.yml, .github/workflows/docs_workflow.yml, .gitmodules, compass/version.py, conda/bootstrap.py, conda/compass_env/spec-file.template, conda/shared.py, docs/developers_guide/quick_start.rst, docs/index.rst, setup.py
This is an updated version of #550 
Checklist
=> Add `jigsaw-python` as a submodule

conda/bootstrap.py
This merge includes fixes to deployment, following installation of Jigsaw and Jigsaw-Python from a submodule.  These include:
* installing cmake into the deployment environment
* removing the `compass.egg-info` directory, which sometimes causes trouble
* including the `/usr/lib64` directory in `LD_LIBRARY_PATH` on Anvil, which seems to be needed to build MPAS-Ocean
* do not remove `jigsaw` and `jigsawpy` when updating an environment
Checklist
=> Several fixes to deployment

compass/ocean/mesh/cull.py
=> Fix typo culeed --> culled

compass/ocean/tests/parabolic_bowl/viz/__init__.py
Invert the x-axis for the parabolic bowl convergence plot
=> Clean-up parabolic bowl convergence plot

compass/ocean/mesh/remap_topography.py
=> Cap fractions from topography to one

compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
=> Don't make DIB files if not ice-shelf cavities

conda/bootstrap.py
=> Add c_stdlib to jigsaw build deps

compass/version.py, conda/compass_env/spec-file.template
=> Update to v1.4.0-alpha.5 and fix matplotlib

compass/version.py, conda/compass_env/spec-file.template
This version requires `matplotlib >= 3.9.1` and `mpas_tools 0.34.1`
Checklist
=> Update to v1.4.0-alpha.6

compass/version.py, conda/compass_env/spec-file.template
This will bring in https://github.com/MPAS-Dev/geometric_features/pull/203, which will add a critical passage for Carroll Inlet near Stange Ice Shelf.
Checklist
=> Update to compass v1.4.0-alpha.7 and geometric_features v1.5.0

.github/workflows/pre_commit_update_workflow.yml
This workflow runs weekly on Wednesday to check for updates to `pre-commit` and its dependencies. If available, the updates will be automatically applied and put into a new PR.
Checklist
=> Add `pre-commit` autoupdate workflow

compass/version.py, conda/compass_env/spec-file.template
Updates:
* `mpas_tools` v1.2.2: This bring in several important bug fixes.
* `esmf` v8.8.1: compatible with dependencies from latest `mpas_tools` and a good idea anyway
* `compass` 1.7.0-alpha.3: As always, because dependencies have changed, this merge update compass' alpha version.
Checklist
=> Update mpas_tools and esmf

compass/ocean/tests/global_ocean/files_for_e3sm/remap_tidal_mixing.py
Some updates required for supporting pyremap 2.0.0 somehow got missed in this particular step.
Checklist
=> Fix remapping of tidal mixing fields

.github/dependabot.yml, .github/workflows/pre_commit_update_workflow.yml
This PR simply adds @andrewdnolan to various lists we have for reviewing CI.
@xylar Review checklist:
=> Add @andrewdnolan to CI reviewers lists

.github/workflows/pre_commit_update_workflow.yml
@xylar I can't request your review so here is your ping! :)
=> Remove @altheaden from reviewer lists
