setup_testcase.py

Since this repo doesn't have any tags yet, `git describe` will fail unless it has an `--always` flag.  This fix is needed before this repo will be useful for testing.

Fix git describe for repo without any tags

---

.gitignore
.gitmodules

This merge adds submodules for [ocean/develop](https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop) and [landice/develop](https://github.com/MPAS-Dev/MPAS-Model/tree/landice/develop).  These submodules will be maintained as the official versions of MPAS-Ocean and MALI that COMPASS is intended to be compatible with at a given time.

Add submodules for ocean/develop and landice/develop

---

azure-pipelines.yml
ci/mpi_mpich.yaml
ci/mpi_nompi.yaml
ci/mpi_openmpi.yaml

Before, it was being installed from the `e3sm` channel, which is not as helpful now that the recipe is local.

Build compass metapackage in Azure

---

ocean/soma/32km/default/config_analysis.xml
ocean/ziso/20km/default/config_forward.xml

There are two testcases that use links to `testing_and_setup/compass` using `mpas_model` as the base.  This was never the intended way of finding contents of testcases, and no longer works now that COMPASS is in its own repo.  These two links have been fixed in this merge.
partially addresses #20

Fix SOMA and ZISO script links

---

setup_testcase.py

This allows config files to use relative paths and have them converted to absolute paths before links are created or files are copied.  This is particularly useful when referring to `MPAS-Model/ocean/develop` or `MPAS-Model/landice/develop`.

Make sure link/copy sources are absolute paths

---

docs/machine_specific_instructions/lanl.rst

LANL IC revamped their documentation, breaking all previous links. These are the fixes. I remade the html page and clicked on the new links to verify.

Update LANL hpc links after they changed

---

ocean/global_ocean/EC60to30wISC/files_for_e3sm/config_files_for_e3sm.xml
ocean/global_ocean/SOwISC12to60/files_for_e3sm/config_files_for_e3sm.xml

The ECwISC and SOwISC meshes are missing this flag as part of the files generated for E3SM

Fix missing --ice_shelf_cavities flag

---

ocean/drying_slope/marsh_flooding/idealized_transect/config_analysis.xml
ocean/drying_slope/marsh_flooding/idealized_transect/config_forward1.xml
ocean/drying_slope/marsh_flooding/idealized_transect/config_forward2.xml
ocean/drying_slope/marsh_flooding/idealized_transect/config_forward3.xml

This bug appeared in linking the python script **`comparison.py`** to the **`script_test_dir`** directory. It intended to provide the path of the python script by using **`path_base`**, which generated to a invalid hyperlink of the script and failed to run the analysis. Changing it to **`source_path`** fixed this issue.

Fix a bug in the marsh_flooding/idealized_transect case

---

README.md
azure-pipelines.yml

This merge also adds a link to the legacy documentation to the README.  Legacy documentation has not yet been created but should be generated by this PR.

Add support for the legacy branch to CI

---

docs/conf.py
docs/index.rst
docs/ocean/test_cases/isomip_plus.rst
docs/ocean/test_cases/isomip_plus_at_lanl.rst
docs/users_guide/overview.rst
docs/versions.rst

This merge:
* Adds a version page to the legacy documentation to point to the stable version
* Has the user check out the `legacy` branch when cloning the repo
* Fixes some old references to `testing_and_setup/compass` in the MPAS-Model repo
* Comments out usage of the `_static` directory in the docs, since this produces a warning when the docs are built.

Update legacy docs

---

ocean/global_ocean/EC60to30wISC/spin_up_EN4_1900/config_initial_state.xml
ocean/global_ocean/EC60to30wISC/spin_up_EN4_1900/config_initial_state_64_levels.xml
ocean/global_ocean/EC60to30wISC/spin_up_phc/config_initial_state.xml
ocean/global_ocean/EC60to30wISC/spin_up_phc/config_initial_state_64_levels.xml
ocean/global_ocean/SOwISC12to60/init/config_initial_state.xml
ocean/global_ocean/config_files_ISC/config_initial_state.xml
ocean/global_ocean/template_initial_state.xml
ocean/isomip/10km/expt1.01/config_init1.xml
ocean/isomip/10km/expt1.01/config_init2.xml
ocean/isomip/10km/expt2.01/config_init1.xml
ocean/isomip/10km/expt2.01/config_init2.xml
ocean/isomip/template_init.xml
ocean/isomip_plus/2km/time_varying_Ocean0/config_adjust_ssh.xml
ocean/isomip_plus/template_init.xml
ocean/iterative_ssh_landIcePressure_scripts/iterate_init.py
ocean/sub_ice_shelf_2D/5km/Haney_number_iterative_init/config_init1.xml
ocean/sub_ice_shelf_2D/5km/Haney_number_iterative_init/config_init2.xml
ocean/sub_ice_shelf_2D/5km/iterative_init/config_init1.xml
ocean/sub_ice_shelf_2D/5km/iterative_init/config_init2.xml
ocean/sub_ice_shelf_2D/5km/restart_test/config_init1.xml
ocean/sub_ice_shelf_2D/5km/restart_test/config_init2.xml
ocean/sub_ice_shelf_2D/5km/template_init.xml
ocean/sub_ice_shelf_2D/5km/with_frazil/config_init1.xml
ocean/sub_ice_shelf_2D/5km/with_frazil/config_init2.xml
ocean/sub_ice_shelf_2D/check_bit_for_bit.py
ocean/sub_ice_shelf_2D/plot_sub_ice_shelf_2D.py

This merge removes references to the `config_iterative_init_variable` namelist option, which was removed in https://github.com/MPAS-Dev/MPAS-Model/pull/812.
It also renames the field `modifySSHMask` to `modifyLandIcePressureMask`, to be consistent with changes in that PR.

Remove config_iterative_init_variable from all tests

---

ocean/drying_slope/init_idealized_transect.xml
ocean/global_ocean/template_init_with_land_ice.xml
ocean/global_ocean/template_initial_state.xml
ocean/isomip/template_init.xml
ocean/isomip_plus/template_init.xml
ocean/scripts/LIGHTparticles/user_nl_mpaso
ocean/sub_ice_shelf_2D/5km/Haney_number_init/config_init1.xml
ocean/sub_ice_shelf_2D/5km/Haney_number_init/config_init2.xml
ocean/sub_ice_shelf_2D/5km/Haney_number_iterative_init/config_init1.xml
ocean/sub_ice_shelf_2D/5km/Haney_number_iterative_init/config_init2.xml
ocean/sub_ice_shelf_2D/5km/restart_test/config_init1.xml
ocean/sub_ice_shelf_2D/5km/restart_test/config_init2.xml
ocean/sub_ice_shelf_2D/5km/with_frazil/config_init1.xml
ocean/sub_ice_shelf_2D/5km/with_frazil/config_init2.xml

In conjunction with https://github.com/MPAS-Dev/MPAS-Model/pull/825, The following namelist changes are needed:
* `config_alter_ICs_for_pbcs` --> `config_alter_ICs_for_pbs` (to support both top and bottom cells)
* `config_pbc_alteration_type` --> `config_pc_alteration_type`
* `config_use_rx1_constraint = .true.` --> `config_init_vertical_grid_type = 'haney-number'` (to support a new `z-level` vertical grid)

Change three init mode namelist options

---

compass/ocean/tests/global_ocean/metadata.py

Put `"not found"` in metadata for missing packages, rather than raising an exception.  We should not require that the `compass` package be present.  I took it out of the test environment and discovered these errors.

Fix metadata for `global_ocean` test group

---

README.md
azure-pipelines.yml
docs/versions.rst
recipe/meta.yaml

The `master` branch here is not necessarily a stable branch, since we don't have a development branch, so the docs should be called `latest` like we do for development branches in most other repos.

Rename docs from master from "stable" to "latest"

---

compass/default.cfg
compass/machines/anvil.cfg
compass/machines/badger.cfg
compass/machines/chrysalis.cfg
compass/machines/compy.cfg
compass/machines/cori-haswell.cfg
compass/machines/cori-knl.cfg
compass/machines/grizzly.cfg
compass/setup.py
compass/suite.py
deploy/build.template
deploy/create_compass_env.py
deploy/load_compass.template
docs/developers_guide/machines/anvil.rst
docs/developers_guide/machines/badger.rst
docs/developers_guide/machines/chrysalis.rst
docs/developers_guide/machines/compy.rst
docs/developers_guide/machines/cori.rst
docs/developers_guide/machines/grizzly.rst
docs/developers_guide/machines/index.rst
docs/index.rst
docs/users_guide/machines/anvil.rst
docs/users_guide/machines/badger.rst
docs/users_guide/machines/chrysalis.rst
docs/users_guide/machines/cori.rst
docs/users_guide/machines/grizzly.rst
docs/users_guide/machines/index.rst
load/get_activation_script.py
load/load_compass_env.sh

This merge adds many features related 
* making activation scripts that 
* activate the ``compass`` conda environment
* loading modules
* setting environment variables (`NETCDF`, `PIO`, etc.)
* Use E3SM compilers and MPI libraries on each machine to build:
* ESMF (needed to make mapping files efficiently)
* SCORPIO
* Documenting these chnages
* Updating the user's guide to make clearer that the instructions won't work yet (not until we have a 1.0.0 release).
As I added to the documentation, with these changes, a developer should now be able to run:
```
source ./load/load_compass_env.sh -m <machine> -c <compiler>
```
in the local compass branch to active the appropriate compass test environment as well as load the system modules and set the environment variables needed to build MPAS in …

Make activation scripts (test envs and releases) on supported machines

---

compass/ocean/suites/sowisc12to60.txt
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
deploy/create_compass_env.py

For systems that work with conda-forge MPI, this should work as normal as long as they use `mpi_run` as their `parallel_executable`.
For supported machines, ESMF will be built as part of deploying compass, and should run with the system libraries that are also used to build MPAS.
This merge adds the ESMF library to the `LD_LIBRARY_PATH` in the activation script.  Testing this PR revealed this problem at least on Anvil.
This merge adds a test suite for the `SOwISC12to60`.  This is for convenience of running the 4 test cases associated with creating an E3SM initial condition (and the performance test case) all in one command, just as with the `EC*30to60` meshes.
closes #58

Require ESMF to run with system MPI 

---

setup.py

Previously, some README files weren't getting linked when running from the package (as opposed to the repo) because the README files aren't included in the package.  This merge fixes that issue.
closes #70

Add README files as package data

---

compass/landice/tests/dome/decomposition_test/__init__.py
compass/landice/tests/dome/restart_test/__init__.py
compass/landice/tests/eismint2/decomposition_test/__init__.py
compass/landice/tests/eismint2/restart_test/__init__.py
compass/landice/tests/enthalpy_benchmark/A/__init__.py
compass/landice/tests/greenland/decomposition_test/__init__.py
compass/landice/tests/greenland/restart_test/__init__.py
compass/landice/tests/hydro_radial/decomposition_test/__init__.py
compass/landice/tests/hydro_radial/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/decomp_test/__init__.py
compass/ocean/tests/baroclinic_channel/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/threads_test/__init__.py
compass/ocean/tests/global_ocean/analysis_test/__init__.py
compass/ocean/tests/global_ocean/daily_output_test/__init__.py
compass/ocean/tests/global_ocean/decomp_test/__init__.py
compass/ocean/tests/global_ocean/dynamic_adjustment.py
compass/ocean/tests/global_ocean/init/__init__.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/performance_test/__init__.py
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/threads_test/__init__.py
compass/ocean/tests/ice_shelf_2d/default/__init__.py
compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
compass/ocean/tests/ziso/default/__init__.py
compass/ocean/tests/ziso/with_frazil/__init__.py
compass/run.py
compass/setup.py
compass/testcase.py
compass/validate.py

Perform all variable comparisons before either raising an exception (in an individual test case) or printing a failure message that separates the "internal" test status from the comparison with the baseline.
closes #59

Change how variable comparison is handled

---

compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/mesh/cull.py
docs/developers_guide/quick_start.rst
recipe/meta.yaml

This merge switches the `global_ocean` test group to using a set of threaded python tools for creating masks.  These same tools are being used in MPAS-Analyisis and have been shown to perform better on larger meshes than the C++ equivalents.
The python version of the transect mask creator also has the advantage that it follows the transect through polygons on the sphere rather than zig-zagging (which has been a problem with `MpasMaskCreator.x`). 
The results with the new tools are not expected to be bit-for-bit as compared with the previous mask creator.  So the test suites should pass but not bit-for-bit for global ocean test cases.
See https://github.com/MPAS-Dev/MPAS-Tools/pull/399

Switch global ocean mesh culling and files for E3SM to use python masks

---

compass/setup.py

This was supposed to happen already but is linking in the base work directory, not the test case's work dir.

Symlink load_compass_env.sh in test case work dirs

---

.gitignore
compass/suite.py

If the repo base is also the work directory (the default), we can't symlink compass to itself.
This merge also adds directories and files related to testing to `.gitignore` in case anyone does use the repo as the work directory.
closes #67

Don't try to symlink compass to itself

---

compass/ocean/namelists/namelist.ssh_adjust
compass/ocean/tests/global_ocean/init/streams.ssh_adjust

Also disable SSH consistency check.
These errors aren't fatal but they mean that the `ssh_adjustment` directory has a number of MPAS-Ocean error files, which looks troubling.  Better to prevent them.
closes #68

Fix mixedLayerDepth (non)output for ssh_adjustment

---

compass/provenance.py

This is causing distracting warnings when working with the compass package in the conda environment.
closes #69

Don't use "git describe" if not in a git repo

---

compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
compass/ocean/tests/global_ocean/make_diagnostics_files/make_diagnostics_files.cfg
docs/users_guide/ocean/test_groups/global_ocean.rst

This is helpful for creating masks and mapping files for meshes that already exist.

Add test case for creating regions masks and mapping files on their own

---

compass/landice/tests/dome/run_model.py
compass/landice/tests/eismint2/run_experiment.py
compass/landice/tests/enthalpy_benchmark/run_model.py
compass/landice/tests/greenland/run_model.py
compass/landice/tests/hydro_radial/run_model.py
compass/ocean/tests/baroclinic_channel/forward.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
compass/ocean/tests/ice_shelf_2d/forward.py
compass/ocean/tests/ice_shelf_2d/ssh_adjustment.py
compass/ocean/tests/ziso/forward.py
compass/step.py
docs/developers_guide/framework.rst
docs/developers_guide/organization.rst

This is more convenient, but means that the model shouldn't actually be added until the necessary config option is available after setup.
This merge moves `add_model_as_input()` to each test cases' `__init__()` 
The docs are updated based on this change.
closes #73

Allow `add_model_as_input()` to be called in `__init__()`

---

compass/landice/tests/enthalpy_benchmark/A/__init__.py
compass/landice/tests/enthalpy_benchmark/B/__init__.py
compass/ocean/tests/global_ocean/configure.py
compass/ocean/tests/ice_shelf_2d/__init__.py
compass/ocean/tests/ziso/__init__.py
compass/setup.py
compass/testcase.py
docs/developers_guide/organization.rst

This means test cases don't need to override the `configure()` method if all they want to do is load the config file `<test_case>.cfg` in the test-case package (directory).
Land-ice and ocean test case and test groups have been updated to no longer load the test case's config file (since this will have already happened automatically).  For now, this doesn't reduce code very much because in all of these cases, the `configure()` method (or shared configure function at the test group level) did more than just load the test case's config options.  But it is likely to make things simpler in the future.
closes #72

Automatically read test-case config files

---

compass/landice/tests/enthalpy_benchmark/A/__init__.py
compass/landice/tests/enthalpy_benchmark/A/visualize.py
compass/landice/tests/enthalpy_benchmark/B/__init__.py
compass/landice/tests/enthalpy_benchmark/B/visualize.py
compass/landice/tests/hydro_radial/setup_mesh.py
compass/landice/tests/hydro_radial/visualize.py
compass/ocean/tests/global_ocean/mesh/so12to60/__init__.py
compass/step.py
docs/developers_guide/organization.rst

This argument is used to make a symlink to a file in the ``compass`` package and set that file as an input to the step.
With this change, it's a lot easier to link files from the package in a similar manner to how we are used to doing this in legacy COMPASS.  You can link geojson files, READMEs or even python scripts that a user should optionally run (e.g. for quick and dirty viz).
The ocean and landice cores have been updated with this change, as has the documentation.
closes #75

Add a `package` argument to `add_input_file()`

---

compass/config.py

Prior to this fix, if you have a `TestCase` child class that is in a module but not a package, it causes a `TypeError` to be raised when looking for a config file in the package (there is no package!).  With this change, we simply catch the exception and move on.

Handle test cases that are not packages

---

compass/ocean/tests/global_ocean/namelist.forward

We have discussed that we do not want to have surface restoring as part of dynamic adjustment anymore.

Turn off surface restoring in global ocean

---

compass/landice/tests/dome/decomposition_test/__init__.py
compass/landice/tests/dome/restart_test/__init__.py
compass/landice/tests/eismint2/decomposition_test/__init__.py
compass/landice/tests/eismint2/restart_test/__init__.py
compass/landice/tests/enthalpy_benchmark/A/__init__.py
compass/landice/tests/greenland/decomposition_test/__init__.py
compass/landice/tests/greenland/restart_test/__init__.py
compass/landice/tests/hydro_radial/decomposition_test/__init__.py
compass/landice/tests/hydro_radial/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/decomp_test/__init__.py
compass/ocean/tests/baroclinic_channel/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/threads_test/__init__.py
compass/ocean/tests/global_ocean/analysis_test/__init__.py
compass/ocean/tests/global_ocean/daily_output_test/__init__.py
compass/ocean/tests/global_ocean/decomp_test/__init__.py
compass/ocean/tests/global_ocean/dynamic_adjustment.py
compass/ocean/tests/global_ocean/init/__init__.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/performance_test/__init__.py
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/threads_test/__init__.py
compass/ocean/tests/ice_shelf_2d/default/__init__.py
compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
compass/ocean/tests/ziso/default/__init__.py
compass/ocean/tests/ziso/with_frazil/__init__.py
compass/run.py
compass/testcase.py
docs/developers_guide/api.rst
docs/developers_guide/organization.rst

The `run()` method previously included validation of variables and timers, but things are cleaner in a few ways if running steps and validation are kept separate:
1. For steps that only need to validate variables or timers, there is no need to override the `run()` method at all, saving a (somewhat confusing) call to `super().run()`.  Since `TestCase.validate()` does nothing, there is no need to call `super().validate()`.
2. In test cases that do override `run()`, it is now clearer that `super().run()` should be called at the end of the new `run()` method to run the steps (e.g. after altering the number of cores that each step should run with based on config options).
All test cases have been updated with this split.
The output from test suites has been altered to indicate if the test, the …

Split `Testcase.run()` into `run()` and `validate()` methods

---

compass/setup.py

This came up in reorganizing #111.
First, it is convenient to add the custom config file to the config options both before and after calling the test case's `configure()` method.  It turns out that you can use config options to determine which steps to add to a test case if you do this.  This is really convenient for defining a flexible parameter study like the convergence test in #111.  You can make the parameter values a config option.  The user could make a custom config file and alter the config options there before setting up the test case.  Depending on how the test case is set up, altering the config options between setup and run might either have no effect (as in #111) or cause you trouble, so that would be something to document as part of each test case that uses this approach. …

Two small fixes to the `setup` module

---

compass/run.py
docs/developers_guide/command_line.rst
docs/users_guide/quick_start.rst

With this merge, if you only set up a single test suite in a work directory, `compass run` will work without the need to specify the suite name.  Since this is by far the most common work flow, this change should save a little trouble nearly every time a test suite is run.

`compass run` runs a single suite without arg

---

compass/default.cfg
compass/run.py
compass/setup.py
docs/developers_guide/command_line.rst

This merge adds the ability for users to choose which steps in a test case they want to run.  They have 2 options.
First, they can alter the `steps_to_run` config option in the `test_case` section at the very top of the test case's config file:
```
[test_case]
steps_to_run = initial_state full_run restart_run
```
The list of `steps_to_run` can be separated by spaces, commas or both.
Or they can specify which steps to run (or which steps not to run) via the ``--steps`` (or ``--no-steps``) flag to ``compass run``:
```
python -m compass run --steps initial_state full_run
python -m compass run --no-steps restart_run
```
Both of these accomplish the same thing -- skipping the ``restart_run`` step of the test case.
The new capability has been added to the documentation.
closes #80

Alter `steps_to_run` in config file or command line

---

compass/io.py
compass/step.py

We don't use the ability to use config options for downloads directly with this function, so this merge eliminates the unused feature.
Cases have arisen where it is useful to have a URL that has a different file name than the target filename that we want to download to.  Sometimes, the URL doesn't have a particularly unique or descriptive name.
This merge also updates the `Step` class to handle the changes in `download()`, making sure URLs include the file name.

Simplify and generalize the `download()` function

---

conda/configure_compass_env.py
docs/developers_guide/machines/anvil.rst
docs/developers_guide/machines/badger.rst
docs/developers_guide/machines/chrysalis.rst
docs/developers_guide/machines/compy.rst
docs/developers_guide/machines/cori.rst
docs/developers_guide/machines/grizzly.rst
docs/developers_guide/machines/index.rst
docs/developers_guide/quick_start.rst

The conda environment is now called `dev_compass_1.0.0` (possibly with the MPI version if using the conda package for MPI) and the activation script starts with `load_dev_compass_1.0.0`.
The documentation has been updated accordingly.

Rename dev. conda env. from `test_compass*` to `dev_compass*`

---

list_testcases.py

After the introduction of the E3SM submodules, `list_testcases.py` now finds some XML files in E3SM that it tries (and fails) to
parse.  One solution would be to have a try/except but the approach taken in this merge is to assume all COMPASS xml files start with `config`.  The XML files from E3SM that are causing trouble do not.

Fix pattern for xml search

---

compass/run.py

They were sometimes displaying odd things like 01:60, but this should now be fixed.

Fix rounding of test and suite runtimes

---

compass/step.py
docs/developers_guide/framework.rst
docs/developers_guide/organization.rst

If ``copy=True``, the file will be copied to the work directory rather than symlinked.
The documentation has been updated to include the new ``copy`` keyword argument.

Add a copy option for input files

---

compass/run.py
docs/developers_guide/command_line.rst
docs/users_guide/quick_start.rst

Allowing the .pickle suffix in the `compass run` command is a convenience
change to support command-line tab completion.

Allow `compass run suitename` to include or not the .pickle suffix

---

compass/list.py
compass/suite.py
docs/developers_guide/organization.rst
docs/users_guide/test_suites.rst

This merge also updates the documentation for this change and adds a
short section to the Developer's Guide about developing suites.

Make 'compass list --suites -v' print the contents of a suite

---

conda/compass_env/spec-file-mpich.txt
conda/compass_env/spec-file-nompi.txt
conda/compass_env/spec-file-openmpi.txt
conda/recipe/meta.yaml
setup.py

This brings in https://github.com/MPAS-Dev/MPAS-Tools/pull/426
Remove unused rasterio and affine dependencies.  These are not needed in compass (they aren't currently used).  Rasterio was removed from MPAS-Tools, and now conflicts with the latest version of that package because they have not been built with the same version of `libnetcdf`.

Update mpas_tools to 0.7.0

---

compass/ocean/tests/gotm/default/init.py

This got missed in #129 because the feature was changed in #142 but I didn't remember to rebase.

Fix updating namelist in gotm/default test case

---

compass/ocean/tests/global_ocean/metadata.py

We were using `ncra` but should have been using `ncks` because we only want to add the metadata, not average the files in time.

Fix appending of global ocean metadata

---

compass/ocean/tests/global_ocean/analysis_test/__init__.py
compass/ocean/tests/ice_shelf_2d/__init__.py
compass/ocean/tests/ice_shelf_2d/forward.py
compass/ocean/tests/ziso/forward.py

The `global_ocean/analysis_test`, both `ice_shelf_2d` test cases, and the `ziso/frazil_test` are all missing output files that should be added with `add_output_file()`.  This was revealed by #151

Add missing output files to 3 ocean test groups

---

compass/setup.py
compass/validate.py
docs/developers_guide/framework.rst

In `compass.validate.compare_variables()`, optionally check to make sure the files being compared are output of one of the steps in the test case.
The new behavior (and the keyword argument for disabling it) are now in the documentation.

Check that files to validate are step output

---

docs/developers_guide/quick_start.rst
docs/glossary.rst
docs/index.rst
docs/tutorials/dev_porting_legacy.rst

This tutorial uses the `gotm` test group and the default test case as an example.

Add a tutorial on porting test groups from legacy

---

compass/landice/tests/dome/decomposition_test/__init__.py
compass/landice/tests/dome/restart_test/__init__.py
compass/landice/tests/eismint2/decomposition_test/__init__.py
compass/landice/tests/eismint2/restart_test/__init__.py
compass/landice/tests/greenland/decomposition_test/__init__.py
compass/landice/tests/greenland/restart_test/__init__.py
compass/landice/tests/hydro_radial/decomposition_test/__init__.py
compass/landice/tests/hydro_radial/restart_test/__init__.py
compass/landice/tests/thwaites/decomposition_test/__init__.py
compass/landice/tests/thwaites/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/decomp_test/__init__.py
compass/ocean/tests/baroclinic_channel/restart_test/__init__.py
compass/ocean/tests/baroclinic_channel/threads_test/__init__.py
compass/ocean/tests/global_ocean/decomp_test/__init__.py
compass/ocean/tests/global_ocean/init/__init__.py
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/threads_test/__init__.py
compass/ocean/tests/gotm/default/__init__.py
compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
compass/ocean/tests/ziso/default/__init__.py
compass/ocean/tests/ziso/with_frazil/__init__.py
compass/validate.py
docs/developers_guide/framework.rst
docs/developers_guide/organization.rst
docs/tutorials/dev_porting_legacy.rst

In `compass.validate.compare_variables()`, skip validation if one or more of the steps involved in the variable comparison were not run.  Log a message in such cases saying why validation was skipped.

Skip steps not run by default in validation

---

compass/ocean/suites/nightly.txt
compass/ocean/tests/ice_shelf_2d/__init__.py
compass/ocean/tests/ice_shelf_2d/default/__init__.py
compass/ocean/tests/ice_shelf_2d/ice_shelf_2d.cfg
compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
compass/ocean/tests/ice_shelf_2d/viz.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/ice_shelf_2d.rst
docs/users_guide/ocean/test_groups/ice_shelf_2d.rst

The z-star versions of the test cases are now in a z-star subdir.
The z-level restart test has been added to the nightly suite.
The cavity thickness has been increased from 10 to 50 m to accommodate the z-level coordinate.

Add z-level ice-shelf 2d test cases

---

conda/configure_compass_env.py

When running `./conda/configure_compass_env.sh` with `--env_name`, the name of the activation script now starts with `load_`.  That prefix was missing before.

Fix activation script name when `--env_name` flag is used

---

compass/validate.py

This merge fixes a bug in the validate package that was not properly
checking if None was passed to the validation function.  This corrects
the following error:
```
File
"/turquoise/usr/projects/climate/mhoffman/mpas/compass/compass/validate.py",
line 124, in compare_variables
internal_pass = _compare_variables(
File
"/turquoise/usr/projects/climate/mhoffman/mpas/compass/compass/validate.py",
line 254, in _compare_variables
result = _compute_norms(slice1, slice2, quiet, l1_norm,
File
"/turquoise/usr/projects/climate/mhoffman/mpas/compass/compass/validate.py",
line 302, in _compute_norms
if max_l1_norm < l1_norm:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
After the fix, the validate package works as expected when passing None
for an norm value (the …

Fix None check of norms in validate package

---

conda/compass_env/spec-file-mpich.txt
conda/compass_env/spec-file-nompi.txt
conda/compass_env/spec-file-openmpi.txt
conda/recipe/meta.yaml

This merge updates `geometric_features` to a new version (0.5.0) that excludes the Mediterranean from the Atlantic MOC.  There is also an `AtlanticMed` MOC basin that still includes the Mediterranean.
This requires a release of geometric_features after https://github.com/MPAS-Dev/geometric_features/pull/176 has been merged.

Update Atlantic MOC basins to exclude Mediterranean

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/ocean_test/__init__.py
docs/developers_guide/ocean/test_groups/isomip_plus.rst
docs/users_guide/ocean/test_groups/isomip_plus.rst

These are the remaining test cases for the `isomip_plus` test group that MPAS-Ocean can currently support (without moving grounding lines).

Add ISOMIP+ Ocean1 and Ocean2 test cases

---

conda/compass_env/spec-file-mpich.txt
conda/compass_env/spec-file-openmpi.txt
conda/configure_compass_env.py
conda/pnetcdf/ci/linux_mpi_mpich.yaml
conda/pnetcdf/ci/linux_mpi_openmpi.yaml
conda/pnetcdf/ci/osx_mpi_mpich.yaml
conda/pnetcdf/ci/osx_mpi_openmpi.yaml
conda/pnetcdf/recipe/build.sh
conda/pnetcdf/recipe/conda_build_config.yaml
conda/pnetcdf/recipe/meta.yaml
conda/pnetcdf/recipe/run_test.sh
conda/scorpio/ci/linux_mpi_mpich.yaml
conda/scorpio/ci/linux_mpi_openmpi.yaml
conda/scorpio/ci/osx_mpi_mpich.yaml
conda/scorpio/ci/osx_mpi_openmpi.yaml
conda/scorpio/recipe/COPYRIGHT
conda/scorpio/recipe/build.sh
conda/scorpio/recipe/conda_build_config.yaml
conda/scorpio/recipe/meta.yaml

Like PNetCDF, SCORPIO can be built as a conda package.  This merge adds the conda recipes for `libpnetcdf` and `scorpio`.  Both packages have been built for OSX and Linux with `mpich` and `openmp`, and uploaded to the `e3sm/label/compass` anaconda channel.
The script for building the compass development conda environment has been updated to use these packages on unknown machines.  For now, I'm using the latest `libnetcdf` (4.8.0) but SCORPIO developers suggested that a slightly older version (4.7.4) might be safer since the newest version hasn't been tested.  I uploaded packages built with this older version (and also rebuilt `mpas_tools` 0.7.0 with that version).  So we have that as a fallback if problems emerge.  I haven't seen any so far.
This work is critical for supporting compass …

Switch Linux and OSX environments to use SCORPIO conda package

---

conda/configure_compass_env.py

With this change, when a developer calls `configure_conda_env.sh` with `--conda`, they can safely use `~` in the path.  This was not working as expected on Chrysalis.

Fix use of "~" in conda base location

---

conda/configure_compass_env.py
docs/developers_guide/machines/index.rst
docs/developers_guide/quick_start.rst

First, this merge adds an error that is raised when the `--mpi` flag is missing (and `--env_only` was not specified) on an "unknown" machine (Linux or Mac).  The hope is to avoid unexpectedly creating an environment without MPI support.
Second, it adds what is hopefully better documentation that clarifies the need to specify the ``--mpi`` flag when installing on an Linux and Mac OS.

Better document and configure conda envs. on Linux and Mac OS

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This should take care of an issue with meshes that are run through `MpasMeshConverter.x` that end up with garbage values in `kiteAreasOnVertex`.  This issue was causing trouble in tests in debug mode, fixed in https://github.com/MPAS-Dev/MPAS-Tools/pull/431

Update `mpas_tools` to 0.8.0 

---

docs/developers_guide/quick_start.rst

@altheaden pointed out that it's pretty confusing to have instructions for setting up a test case or suite before the instructions for building the model, since the command for setting up the suite fails when the model hasn't been build yet.

Move "Building MPAS components" earlier in the developer's quick start

---

compass/ocean/tests/isomip_plus/ocean_test/__init__.py

These values are needed in order to aggregate the maximum number of cores needed for a suite including these tests.

Set ISOMIP+ cores and min_cores during setup

---

compass/default.cfg
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
compass/ocean/tests/global_ocean/mesh/cull.py
compass/run.py
conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This is useful because the `scipy` engine seems to perform well on Anvil and Chrysalis, whereas the `netcdf4` engine seems to be hanging.
This merge also updates subprocess calls in `global_ocean` to specify the NetCDF engine.
This requires https://github.com/MPAS-Dev/MPAS-Tools/pull/434
closes #185

Add support for specifying the NetCDF output engine

---

docs/design_docs/cached_outputs.rst
docs/design_docs/index.rst

This is being implemented in #184

Add a design document for cached output files

---

compass/clean.py
compass/setup.py
compass/suite.py
docs/developers_guide/command_line.rst
docs/users_guide/quick_start.rst

This is convenient for running several test cases in one command even if they aren't part of a predefined test suite.  Test cases are run in the order they are supplied to `compass setup`.
Some functionality has been moved from the `suite` module into `setup` and `clean` to facilitate setting up and cleaning up custom test suites in the same way as predefined ones.
A small bug has been fixed in determining the number of cores that a suite requires.  Previously, all steps were used.  With the fix, only `steps_to_run` are used.
The docs have been updated to include new custom suites.

Make `compass setup` create a custom test suite

---

compass/ocean/tests/global_ocean/metadata.py

In the global ocean test group, we use the name and email address from `git` by default.  If these are not provided, the error message:
```
subprocess.CalledProcessError: Command '['git', 'config', 'user.name']' returned non-zero exit status 1.
```
isn't very helpful.  This merge provides what is hopefully a more helpful error message.

Clarify error when git username or email not set

---

compass/ocean/tests/global_ocean/configure.py
compass/ocean/tests/global_ocean/metadata.py

When setting up global ocean test cases, check for a git username and email address.  This way, any issues are caught during setup rather than showing up as relatively hidden errors at runtime.

Check git username and email during setup

---

compass/ocean/tests/global_convergence/cosine_bell/__init__.py

This requires adding the default steps at init, rather than during configure.  If a user provides different resolutions in a config file, the default steps are removed and new ones are added when the configure() method gets called during setup.
closes #199

List default steps in cosine_bell test case

---

docs/developers_guide/quick_start.rst

This merge makes the dummy path name for the `--conda` flag in the deployment script more verbose: `conda_path` --> `base_path_to_install_or_update_conda`.  The hope is that this makes clear what is stated in the text immediately below, that the path is not just for an existing Miniconda3 installation but also for a new installation if Miniconda3 is not yet installed.

Make conda path dummy name more verbose

---

compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/init/initial_state.py

This merge also adds `graph.info` as an output in the `initial_state` step so it is available to subsequent test cases and steps.
This change means that forward steps depend only in steps from the init test case, not the mesh test case, which should decrease dependencies when running cached versions of each test case (#184).
Various strings have also been switched from the less readable `.format()` syntax to the more readable f-string syntax.

Switch global ocean forward steps to use graph.info from initial state, not mesh

---

compass/ocean/tests/global_ocean/analysis_test/__init__.py
compass/ocean/tests/global_ocean/performance_test/__init__.py
compass/ocean/tests/ziso/default/__init__.py
compass/validate.py

The method for finding the baseline path for the test case has been updated.  It should come from the `test_case` object, not from a config option.
The API of the `compare_timers()` function needed to change to accommodate change to where the baseline directory is stored.  The 3 test cases that use timers have been updated with the new API.

Fix timer comparison with baseline

---

compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/streams.template
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/streams.template
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/streams.template
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/streams.template

This merge turns on global stats in dynamical adjustment test cases.  This is very useful for debugging spin-up issues, particularly with the mean KE and the global CFL.
This merge also adds one step to the EC30to60 dynamic adjustment with the intention of fixing NaNs that were seen in the final `simulation` step before this merge.  This new step has smaller time steps than the final `simulation` step and also has no Rayleigh damping.
partially addresses #208

Fix EC30to60 dynamical adjustment

---

compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/streams.init

We do not deepen critical passages in any mesh configuration, so the critical_passages mask is not needed during init. Requiring the file in `stream.ocean` makes it difficult to swap the mesh used in `initial_state` for another mesh (e.g. one generated on a different machine or with a previous version of compass).
closes #204

Remove `critical_passages` stream from `initial_state` in `global_ocean` test group

---

compass/ocean/suites/nightly.txt

As discussed in https://github.com/MPAS-Dev/compass/discussions/188, we do not plan to use these initial conditions in E3SM runs so it doesn't make sense to test them on a regular basis.

Remove EN4_1900 and PHC_BGC test from nightly suite

---

compass/ocean/tests/global_ocean/daily_output_test/__init__.py
compass/ocean/tests/global_ocean/decomp_test/__init__.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/performance_test/__init__.py
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/threads_test/__init__.py

Rather than assuming that every forward step has an output called `output.nc`, this merge adds that output explicitly when it is needed (which is true for most steps).  The only steps that currently don't produce this output are the shorter dynamic adjustment steps.
closes #205

Global ocean forward steps explicitly add output.nc

---

docs/design_docs/cached_outputs.rst
docs/developers_guide/framework.rst
docs/developers_guide/quick_start.rst

1. State that only `bash` is supported in the developer's guide. We don't create activation scripts for `csh` or equivalent.
2. Remove `json` code tags in a design doc.  Sphinx doesn't recognize them.
3. Make section symbols consistent in framework section of the developer's guide.  Recent changes used tildes (`~`) instead of carrots (`^`).  Now using tildes for all subsections.

A bit of cleanup to the docs

---

conda/configure_compass_env.py

In the script for setting up the compass conda environment, make sure the `conda_base` path (passed in from `--conda` or supplied as a config option) is an absolute path.  Recent tests showed that a relative path resulted in failures when trying to activate the environment.

Make `conda_base` an absolute path

---

compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/namelist.split_explicit

This merge
* uses the same namelist options for SOwISC12to60 as in E3SM 
* reduces the Rayleigh damping in the damped steps
* reduces the barotropic time step to match E3SM
* extends the duration of the existing damped steps
* adds an additional step that runs without damping but with the reduced (5-minute) time step for 10 days
The total adjustment time is extended from 20 to 50 days.  This appear to be necessary to get through some periods of high wave activity during the first 30 to 40 days.
Why exactly the dynamic adjustment that worked before no longer runs successfully is not clear.  It could be the new JIGSAW version, which generates a different mesh and could therefore change the interaction of waves with ice-shelf cavities, but that's pure speculation.
closes #208

Fix dynamic adjustment test case for SOwISC12to60 mesh

---

docs/index.rst
docs/tutorials/dev_add_test_group.rst
docs/tutorials/dev_porting_legacy.rst

This merge also includes some clean up on the tutorial for developers that describes porting a "legacy" test group.

Add tutorial for developers on creating a test group

---

conda/configure_compass_env.py

If the environment name is given manually and it includes the mpi type, it should not redundantly be added to the activation script.

Avoid redundant activation script name

---

compass/ocean/streams/streams.frazil
compass/ocean/streams/streams.land_ice_fluxes
compass/ocean/streams/streams.output
compass/ocean/streams/streams.ssh_adjust
compass/ocean/tests/baroclinic_channel/forward.py
compass/ocean/tests/global_convergence/cosine_bell/forward.py
compass/ocean/tests/global_ocean/analysis_test/streams.forward
compass/ocean/tests/global_ocean/daily_output_test/streams.forward
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
compass/ocean/tests/global_ocean/init/streams.ssh_adjust
compass/ocean/tests/global_ocean/streams.forward
compass/ocean/tests/gotm/default/forward.py
compass/ocean/tests/ice_shelf_2d/forward.py
compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/ziso/forward.py
compass/ocean/tests/ziso/streams.analysis

This merge adds  new streams template for double-precision output.  It makes other templates explicitly double precision and updates all `forward` and `ssh_adjustment` steps with new streams template.
For analysis steps steps, the streams files have been updated for double precision as well.

Switch to double output

---

compass/parallel.py
compass/run.py

Add a check to all types of calls to `compass run` (suites, test cases and steps) to make sure that, on machines with Slurm, we are running on a compute node (i.e. `$SLURM_JOB_ID` is defined).

Check compass run for compute node

---

conda/compass_env/spec-file.template
conda/pnetcdf/ci/linux_mpi_mpich.yaml
conda/pnetcdf/ci/linux_mpi_openmpi.yaml
conda/pnetcdf/ci/osx_mpi_mpich.yaml
conda/pnetcdf/ci/osx_mpi_openmpi.yaml
conda/pnetcdf/recipe/meta.yaml
conda/scorpio/ci/linux_mpi_mpich.yaml
conda/scorpio/ci/linux_mpi_openmpi.yaml
conda/scorpio/ci/osx_mpi_mpich.yaml
conda/scorpio/ci/osx_mpi_openmpi.yaml
conda/scorpio/recipe/meta.yaml

Packages on conda-forge are migrating to this version so compass should, too.

Update to libnetcdf 4.8.1

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This gets rid of the dependency on `pyflann` and uses `scipy`'s `KDTree` instead.
With this change, `WC14` and `SOwISC12to60` meshes are expected to see small but non-bit-for-bit changes because the signed distance functions used to create them are computed with this new approach.

Update to `mpas_tools` v0.11.0

---

deploy/create_compass_env.py
recipe/meta.yaml

We should update the legacy environment once `mpas_tools 0.11.0` is released, including dropping `pyflann` and instead using `scipy.spatial.KDTree`.
We still need to support legacy for now because coastal tests have not been ported to the new package.

Update legacy compass environment

---

docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/index.rst
docs/users_guide/ocean/test_groups/index.rst

This merge adds the missing links to the internal-wave test group in the User's and Developer's Guides, and adds all public classes and methods to the API.

Add a few missing pieces to internal_wave docs

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/isomip_plus/initial_state.py
compass/ocean/tests/isomip_plus/isomip_plus.cfg
compass/ocean/tests/isomip_plus/namelist.time_varying_forcing
compass/ocean/tests/isomip_plus/ocean_test/__init__.py
compass/ocean/tests/isomip_plus/streams.time_varying_forcing
docs/developers_guide/ocean/test_groups/isomip_plus.rst
docs/users_guide/ocean/test_groups/isomip_plus.rst

For now, this is just supported for `Ocean0` (a warm-cavity experiment) but could easily be added for other experiments.

Add a version of ISOMIP+ test cases with time-varying ice-shelf thickness (pressure)

---

compass/ocean/rpe.py
compass/ocean/tests/baroclinic_channel/rpe_test/analysis.py
compass/ocean/tests/baroclinic_channel/rpe_test/streams.forward
compass/ocean/tests/internal_wave/rpe_test/analysis.py
compass/ocean/tests/internal_wave/rpe_test/streams.forward

This PR adds the computation of Reference Potential Energy (RPE) and a timeseries plot to the analysis step for existing RPE tests for internal wave and baroclinic channel test cases. The details of this computation are in Petersen et al. (2015) https://doi.org/10.1016/j.ocemod.2014.12.004. The timeseries plot is also modeled after figures in that publication.

Add RPE analysis to RPE tests

---

conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml

`mache` 1.1.4 includes a bug fix that replaces the `$SHELL{}` directive with `$()` in environment variables.

Update to mache>=1.1.4

---

compass/step.py
docs/developers_guide/api.rst
docs/developers_guide/organization.rst

This is similar to the approach for updating namelist files, and can be used when config options that users might edit could affect things like output interval.

Add method for updating streams files at runtime

---

conda/bootstrap.py

Before this fix, specifying a machine name to the configure script in fact resulted in `machine = None`, which is obviously not the desired behavior.
This likely went unnoticed for 2+ months because we typically let the machine name be discovered automatically.

Fix machine name arg in conda configure script

---

conda/bootstrap.py
conda/shared.py

This makes it easier to test with local builds of dependenciesvlike `mpas_tools`.
Also, begin the process of switching the bootstrap script to f-strings.  Whereas the main configure script has to work for older python versions, the bootstrap script doesn't and should therefore use f-strings for better clarity.

Add `--use_local` flag to conda configure script

---

conda/compass_env/spec-file.template
conda/pnetcdf/ci/linux_mpi_mpich.yaml
conda/pnetcdf/ci/linux_mpi_openmpi.yaml
conda/pnetcdf/ci/osx_mpi_mpich.yaml
conda/pnetcdf/ci/osx_mpi_openmpi.yaml
conda/pnetcdf/recipe/meta.yaml
conda/recipe/meta.yaml
conda/scorpio/ci/linux_mpi_mpich.yaml
conda/scorpio/ci/linux_mpi_openmpi.yaml
conda/scorpio/ci/osx_mpi_mpich.yaml
conda/scorpio/ci/osx_mpi_openmpi.yaml
conda/scorpio/recipe/meta.yaml

This version generalizes the `check_call()` function with logging to include arguments such as `env` for passing environment variables.  This functionality is needed for task parallelism, in which we will want to make different calls in parallel with different sets of environment variables (notably, different numbers of OpenMP threads).
This merge also updates the hdf5 version for the `libpnetcdf` and `scorpio` conda package to v1.12.1 to stay in sync with conda-forge and MPAS-Tools.
Packages uploaded to `e3sm/label/compass`:

Update to MPAS-Toos 0.12.0

---

azure-pipelines.yml
compass/default.cfg
conda/compass_env/spec-file.template
conda/recipe/meta.yaml

Now that dependencies are available, allow python 3.10 (if a user explicitly asks for it).

Switch default python version to 3.9

---

compass/parallel.py
compass/run.py

Rather than relying on the `mache` config file, get the number of cores per node from Slurm.  Warn users if this number differs from what `mache` suggests.

Set the cores per node from Slurm command

---

compass/parallel.py

The call now specifies the current partition, rather than getting the minimum for all partitions.
fixes #282

Fix call to determine cpus per node

---

compass/run.py

This will produce a more helpful error message if a user tries to run on a login node.

Check parallel file system before sinfo call

---

compass/list.py

Cached steps are now listed without it appearing as if they are their own test cases.
closes #293

Update `compass list --suite -v` for cached steps

---

compass/setup.py

If the user provides a config file but that file isn't found, there was previously no error message but obviously no config options were added.  This merge adds an error message if the file doesn't exit.

Add an error message if user config not found

---

compass/setup.py

In #300, I forgot to include a check that a config file was even provided before I checked to see if that file exists.  That causes `compass setup` to fail when a config file is *not* provided.  This PR fixes that blunder.
This goes to show that no PR is too small to get *proper* testing :-(

Fix check for missing config file

---

docs/developers_guide/quick_start.rst

Hi Xylar, 
I've added a sentence in the compass developers' guide describing the path to a config file after a flag `-f` for users to avoid confusion in setting up test cases on COMPASS.
Please review this if this addition is clear and sound. 
Thank you,
Holly

Add a description on the path to config files

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml
setup.py

This is needed until https://github.com/pyamg/pyamg/issues/307 is addressed, likely via https://github.com/pyamg/pyamg/pull/308 and a patch or new release is on conda-forge.

Constrain `scipy <1.8.0`

---

compass/landice/landice.py
compass/landice/mesh.py
compass/landice/tests/humboldt/mesh.py

Create module compass.landice.landice that will contain functions for general use in creating landice meshes, and add flood_fill() function. Also add usage example in Humboldt mesh creation step. The flood_fill() function will likely be used by all landice test groups that interpolate gridded observational data onto an MPAS mesh.

Generalize flood-fill routine for use by multiple test groups

---

compass/landice/mesh.py
compass/landice/tests/humboldt/mesh.py

Add set_geom_points_and_edges() function to compass.landice.mesh module, and call from build_cell_widths(). This will likely be used by all landice mesh-generating test cases.

Add set_geom_points_and_edges() function

---

compass/landice/mesh.py
compass/landice/tests/humboldt/humboldt.cfg
compass/landice/tests/humboldt/mesh.py
docs/users_guide/landice/test_groups/humboldt.rst

Create a function to determine cell_width based on input parameters in the config file. This currently contains three different cell spacing functions based on log10(speed), distance to ice edge, and distance to the grounding line that can be turned on or off in the config file. Minimum and maximum cell width and the distances over which cell width is varied are also set in the config file. Implement a use case for Humboldt and update User's Guide. This will be used by all mesh-generating land ice test cases based on real-world geometries.
Note: The mesh created here is not bit-for-bit with the previous version. It is not clear why this is the case, but the differences are trivial.

Create set_cell_width() function

---

compass/landice/mesh.py
compass/landice/tests/humboldt/mesh.py

Add new function compass.landice.mesh.get_dist_to_edge_and_GL() that calculates the distance from each grid point in gridded dataset to the ice margin and grounding line, which is then passed to compass.landice.mesh.set_cell_width() as input to the cell spacing functions. Add use case for Humboldt.

Create function to calculate distance to ice edge and grounding line

---

conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml

This version brings in important module update on Cori-Haswell and Chrysalis.
This merge also makes a change that helps with testing `mache`:  In addition to getting packages for the compass env from local builds when `--use_local` is provided, do the same for the temporary install environment so a local build of `mache` can be used.  This allows me to build `mache` locally and use it for making the `compass` conda environment.

Update to `mache >=1.2.1`

---

compass/ocean/tests/global_ocean/namelist.forward

Based on testing with the EC30to60 mesh, this seems necessary to avoid spurious surface temperature extrema.

Increase `config_Redi_min_layers_diag_terms` to 8

---

compass/ocean/tests/global_ocean/dynamic_adjustment.py
compass/ocean/tests/global_ocean/global_ocean.cfg

This will hopefully catch issues like #308

Add validation of max temp. during dynamic adjustment

---

conda/bootstrap.py
conda/compass_env/load_compass.template
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml

The two are combined and no longer in lists or dictionaries.
This merge also updates to `mache >=1.3.0`.

Update module commands and env vars for new mache

---

compass/ocean/tests/global_ocean/init/namelist.init

At @mark-petersen's request, we perform 6 iterations of smoothing with a weight of 0.9.
For more info on the smoothing approach, see:
https://github.com/MPAS-Dev/MPAS-Model/pull/440
For more on some slightly more aggressive values used previously (related to ice-shelf cavities), see:
https://github.com/MPAS-Dev/MPAS-Model/pull/532#issuecomment-620760208
Partially addresses #308

Add bathymetry smoothing to global ocean init

---

compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/namelist.rk4
compass/ocean/tests/global_ocean/mesh/qu240/namelist.split_explicit
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/__init__.py

This merge re-enables surface restoring of tracers in the dynamic adjustment test cases from the global ocean test group. This choice was discussed at length in #308.
This merge also enables GM in the QU240 configuration to be (somewhat) more consistent with other resolutions.  QU240 also enables many features that are not used at other resolutions.

Turn on surface restoring for all dynamic adjustment

---

conda/recipe/meta.yaml

This merge adds the python version to the build string so each python version gets its own package, which is necessary given that each package supports only that version of python.

Fix conda package string

---

conda/bootstrap.py

This happens when the number of files or directories changes in the middle of updating permissions on the conda or spack environment (often because the same user or someone else is modifying it).

Fix out-of-range problem with permissions progress bar

---

compass/load/__init__.py
compass/load/load_script.template
conda/recipe/meta.yaml
setup.py

The `compass.load` package and the `create_compass_load_script` command-line tool can be used to generate a load script when `compass` is installed as a conda package, rather than cloning the git repository.

Add load package to compass

---

docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/soma.rst
docs/developers_guide/ocean/test_groups/ziso.rst
docs/users_guide/machines/anvil.rst
docs/users_guide/machines/badger.rst
docs/users_guide/machines/chrysalis.rst
docs/users_guide/machines/compy.rst
docs/users_guide/machines/cori.rst
docs/users_guide/machines/grizzly.rst
docs/users_guide/ocean/test_groups/ziso.rst
docs/users_guide/quick_start.rst

This merge includes updates to the documentation, particularly related to recent expansion of the ZISO test cases (#306) and the way to use compass on unknown (Linux or OSX) machines, following #340.

More updates and corrections to the documentation

---

docs/users_guide/machines/cori.rst
docs/users_guide/machines/grizzly.rst

This merge removes some instructions that are valid for legacy compass, not the 1.0.0 release.  It also removes the remaining warning notes about the user's guide not being valid until a release is made.

A few more small fixes to the User's Guide

---

compass/setup.py

If the number of cores for a step hasn't been set, raise a useful error that gives the test case and step.

Add error check for cores not set

---

azure-pipelines.yml

The v1.0.0 tag didn't create docs as it was supposed to.  These missing quotes should help.

Fix docs deployment on tag

---

compass/machines/default.cfg
compass/parallel.py
docs/users_guide/machines/index.rst
docs/users_guide/quick_start.rst
example_configs/landice.cfg
example_configs/ocean.cfg

For non-HPC machines, it's typically fine to just detect the number of available cores.
This should reduce the amount of information needed in a user config file.

Automatically get `cores_per_node` on single node

---

compass/landice/tests/circular_shelf/albany_input.yaml
compass/landice/tests/circular_shelf/namelist.landice
compass/landice/tests/greenland/albany_input.yaml
compass/landice/tests/greenland/decomposition_test/__init__.py
compass/landice/tests/greenland/streams.landice

Update the MALI-Dev submodule. This brings in the merge of https://github.com/MALI-Dev/E3SM/pull/18.  This also adds updates for COMPASS tests to work with the current version of Albany supported by COMPASS.

Update MALI-Dev submodule

---

compass/landice/tests/eismint2/namelist.landice

This merge updates the MALI submodule to bring in the newly merged PR
https://github.com/MALI-Dev/E3SM/pull/26
This change necessitated a namelist change to the EISMINT2 tests to
maintain the existing (correct) functionality for those tests. This change 
is included in this PR.
Note that the MALI update changes answers for the greenland tests, but
in that case we want to switch to the new functionality (ignoring
positive SMB in ice-free areas).

Update MALI submodule & adjust EISMINT2 test case

---

compass/version.py
conda/bootstrap.py
conda/compass_env/spec-file.template
conda/default.cfg
conda/recipe/meta.yaml
conda/scorpio/recipe/build.sh
conda/scorpio/recipe/meta.yaml

E3SM was updated to this version in https://github.com/E3SM-Project/E3SM/pull/4858
Because a new Spack build is required for this, the compass version has been updated to 1.1.0-alpha.2.  (This should be easy to deploy because most packages will be reused from the 1.1.0-alpha.1 Spack environments.)
closes #339

Update to scorpio 1.3.2

---

compass/landice/tests/greenland/__init__.py
compass/landice/tests/greenland/high_res_mesh/__init__.py
compass/landice/tests/greenland/high_res_mesh/high_res_mesh.cfg
compass/landice/tests/greenland/mesh.py
docs/developers_guide/landice/api.rst
docs/developers_guide/landice/test_groups/greenland.rst
docs/users_guide/landice/test_groups/greenland.rst

Add a test case `landice/greenland/high_res_mesh` that creates a variable resolution Greenland Ice Sheet mesh. Default settings are for 3–30km resolution, mesh density based on observed ice speed and distance to ice margin, and culling ice-free cells >10 km from the ice sheet margin. Resolution, mesh density functions, and cull distance can be set by the user in `high_res_mesh.cfg`. This is based on the `landice/humboldt/default` and `landice/thwaites/high_res_mesh` test cases.

Add Greenland mesh generation test case

---

conda/bootstrap.py

An error message now has f-strings rather than normal strings, as intended.

Fix a typo in error message in env setup

---

compass/version.py
conda/bootstrap.py
conda/recipe/meta.yaml

This seems to be a problem with standalone MPAS builds.  It was introduced in #359, apparently with insufficient testing.
Part of this fix is some patching of SCORPIO 1.3.2 in our spack branch.

Disable timing in scorpio build

---

conda/bootstrap.py
conda/shared.py

A developer can call `./conda/configure_compass_env.py` with `--without_openmp` to prevent this variable from being set.
closes #347

Set `OPENMP=true` in load script by default

---

compass/run/serial.py

This way you don't have to wait until the end of the suite to see how long things are taking.
closes #368

Print runtime for tests as suite runs

---

conda/bootstrap.py

When creating (or updating) the compass environment, it is not necessary to check or change permissions unless we are modifying the shared conda or spack environments.  This merge removes unnecessary attempts to change permissions.

Skip permissions update if not needed

---

conda/bootstrap.py

This update to the conda environment causes problems if it happens in the middle of running with the conda environment elsewhere.  (A likely time this might happen is when creating a build matrix with many compilers and/or MPI implementations, where you want to start running before all builds have completed.)  It was always intended as a "safety" measure to ensure that ESMF comes from spack when we want that.  There's no indication that isn't happening anyway.

Don't remove `esmf` from conda environment

---

compass/load/__init__.py
conda/recipe/meta.yaml

This was not changed when the version migrated to its own module.
A test has also been added to the conda recipe (and therefore CI) that would have caught this.

Fix version import in compass load package

---

compass/provenance.py
compass/setup.py

This is needed for both provenance and test cases, and will also be needed for job scripts.
For provenance, it is necessary to have config options that come from most sources (defaults, mache, machine-specific, MPAS-core and user) but where a test group and test case has not yet been determined so those are not included.
Previously, the framework redundantly made new "basic" config options as a starting point for each test case, adding more config options for the test group and test case, and to call the test case's `configure()` method.
That code was duplicated because it initially seemed trivial but slowly got more complex. For #376, I needed this "basic" set of config options in a 3rd place (for making job scrips) and it was clearly time to fix the unnecessary duplicate code.

Create basic config for an MPAS core

---

conda/bootstrap.py
conda/shared.py
conda/unsupported.txt

When you configure the compass environment, you can pass a list of compilers and a corresponding list of MPI libraries, or you
can pass "all" for one or both of these.  If you leave either blank (or both), the default for the machine is used.  If you pass "all" for either or both, only supported compiler/MPI pairs are used.
This merge also adds some missing combination of machines, compiler and MPI libraries to the list of unsupported configurations.

Optionally build load scripts for multiple compilers/MPIs at the same time

---

conda/bootstrap.py
conda/compass_env/load_compass.template
conda/configure_compass_env.py
conda/shared.py

The verbose output from mamba and from installing the compass package is distracting and confusing to developers.

Simplify output from config compass and load script

---

compass/default.cfg
compass/job/__init__.py
compass/job/template.sh
compass/machines/badger.cfg
compass/machines/cori-haswell.cfg
compass/setup.py
docs/users_guide/quick_start.rst

On supported machines, write out a job script during setup.  The job script uses `mache` to figure out what account, partition, QOS and constraint to use.  It defaults to 1 hour wall-clock time (typically, more than enough) and determines the number of nodes based on the geometric mean (often a practical compromise) of the minimum and target number of cores required for a test case or suite.
Users (and developers) can alter the defaults with a config file, as detailed in the updated User's Guide.

Write out a job script for suite and test cases during setup

---

compass/ocean/tests/global_ocean/daily_output_test/__init__.py

The missing output causes validation to fail.

Fix missing output for daily stats test

---

compass/landice/tests/humboldt/mesh.py

Change config section name from humboldt to humboldt_mesh. This was
causing the mesh_gen test case to fail.

Fix config section name for humboldt_mesh

---

compass/landice/tests/thwaites/high_res_mesh/high_res_mesh.cfg
compass/landice/tests/thwaites/mesh.py

Update default mesh config options to use ice speed and distance to grounding line, but not distance to ice ege in defining cell spacing. Testing indicates this gives a slightly cleaner mesh. Also rename mesh file from Thwaites_1to8km.nc to Thwaites.nc to prevent confusion when using non-default mesh resolution config options.

Update default thwaites high_res_mesh config options

---

conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml

Before, we allowed updates to the latest `mache`, but this causes problems because shared Spack environments may not exist for that `mache` version yet.

Constrain mache version exactly

---

compass/version.py
conda/bootstrap.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/default.cfg
conda/recipe/meta.yaml
conda/shared.py
conda/spack/badger_gnu_mvapich.yaml
conda/spack/badger_gnu_openmpi.yaml
docs/developers_guide/quick_start.rst

Similarly to Albany, these are optional and can be added with `--with_netlib_lapack` and `--with_petsc` flags to `./conda/configure_compass_env.py`.
A new version of `mache`, 1.4.1, is required to support this. Separate spack environments are created depending on whether Albany, Netlib-LAPACK and/or PETSc are included.  This is because:
1. The default environment uses optimized LAPACK (usually from MLK), which is incompatible with Netlib-LAPACK
2. PETSc and Trilinos are monsters, which make loading the Spack environment pretty slow, so we don't want to include them if they aren't needed
This makes for a bit of extra deployment work for me (offset by the recent work to support a matrix of compilers and MPI libraries).

Add PETSc and Netlib-LAPACK to Spack

---

compass/ocean/tests/global_ocean/metadata.py

For CF compliance, global attributes should not have hyphens.

Remove hyphens from some global ocean attributes

---

compass/validate.py

The consequence is that validation will not notice situations where one array has fill values and the other does not.

Ignore fill values during variable validation

---

conda/bootstrap.py
utils/matrix/setup_matrix.py

This merge adds a check for an environment variable `$NO_COMPASS_REINSTALL` before reinstalling compass in edit mode from the current branch.
This is used in calls to `compass setup` within a matrix build.  Without this change, some runs might get disrupted because the `compass` executable or package is not available for a short time during reinstallation.

Add a flag to prevent the compass package from being reinstalled with the load script

---

compass/run/serial.py
compass/step.py
compass/testcase.py
docs/developers_guide/organization.rst

This will enable calls to external packages that may, in turn, call subprocess.  If this functionality is called directly, there is no obvious way to capture stdout/stderr in a log file.  One example of this is jigsawpy's functionality for creating icosahedral meshes.

Optionally run steps as subprocesses

---

compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg
compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg
compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg
compass/step.py

Values were intended for task parallelism but are no longer relevant.

Remove all occurrences of "max_disk"

---

compass/machines/conda-osx.cfg
conda/bootstrap.py

Previously, there was confusion between just "clang" and "gfortran-clang" as the compiler choice.  Now, we just stick with "clang" everywhere (with the understanding that gfortran is still used as the Fortran compiler).
closes #399

Fix automatic choice of compiler and MPI for OSX

---

compass/run/serial.py

These calls caused weird output:
```
Baseline validation failed
NoneType: None
```
because there is no exception or stack trace to print.

Fix calls to `logger.exception()` not in `except` block

---

setup.py

The GOTM test case needs to include a file with this extension.

Add `.nml` files to python package

---

conda/bootstrap.py

We only want to create the `load_latest_compass...` symlinks if we aren't creating an environment with special libraries like Albany, NetLib LAPACK or PETSc.

Fix symlinks to latest compass load scripts

---

compass/run/serial.py

When test cases are run on their own, they don't put a log file in `case_outputs` so we shouldn't incorrectly point to one.
This merge also clean things up by converting calls to the `.format()` method to f-strings.
closes #398

Give log path for failed tests only in suite

---

compass/ocean/tests/internal_wave/initial_state.py

Omitting `mode='init'` seems to have lead to any namelist replacements given at runtime being ignored. This fix lead me to a secondary bug, where we were attempting to add floats to the namelist file. These issues may lead to non-bit-for-bit changes in `internal_wave` runs.

Fix namelist errors in internal_wave

---

compass/logging.py

The function `log_function_call()` is similar to `log_method_call()` but for functions instead of methods.
This will be useful in future work where we are changing some methods to be functions instead.

Add function for logging function calls

---

compass/run/serial.py
compass/testcase.py
docs/developers_guide/api.rst
docs/developers_guide/framework.rst
docs/developers_guide/organization.rst

I moved all run operations from `testcase.run()` and various other internal methods to `run/serial`. This will allow future task parallel modifications to be limited to the run module. The `run()` method in `testcase` will be deprecated in favor of using `step.runtime_setup()` for custom setup operations at runtime. 
I have tested this change by running the `nightly` suite against the baseline without any issues. I'll be making some changes to the documentation as well to account for the changes to the framework.

Move run operations from `testcase` to `run/serial`

---

compass/ocean/tests/baroclinic_channel/default/__init__.py

The default baroclinic channel test case was missing the comparison step. This is the first test in the nightly suite, so it is useful to immediately see if the comparison is working.

Add comparison to default baroclinic channel

---

compass/ocean/tests/global_ocean/analysis_test/__init__.py

As of https://github.com/E3SM-Project/E3SM/pull/5099, this variable is no longer part of the AM and is instead part of the main MPAS-Ocean code.

Remove `dThreshMLD` validation from mixedLayerDepth AM

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/e3sm_to_cmip_maps.py
compass/ocean/tests/global_ocean/files_for_e3sm/scrip.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
compass/ocean/tests/global_ocean/make_diagnostics_files/make_diagnostics_files.cfg
compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg
compass/parallel.py

To make things easier for the team publishing CMIP6 data from E3SM simulations, we want a set of mapping files from each MPAS-Ocean (and -Seaice) mesh to a standard CMIP6 grid.  This merge adds a step to the `files_for_e3sm` test case for making these mapping files.
It also adds this capability to the `make_diagnostic_files` to test case so these mapping files can be created (along with other diagnostics files) for existing meshes.

Add a step for making mapping files for `e3sm_to_cmip`

---

compass/default.cfg
compass/setup.py
compass/step.py
compass/suite.py
docs/users_guide/quick_start.rst

A directory (either `mpas-ocean` or `mpas-albany-landice`) is made within the base of the work directory and the MPAS model executable (`ocean_model` or `landice_model`) is copied there.  Symlinks within the work directory are to that copy.
This is useful if you want to delete the E3SM branch used to set up test cases or suites but you still want the ability to run the code after the fact.
closes #345

Copy MPAS model executable to work directory

---

utils/bisect/README.md
utils/bisect/bisect.py
utils/bisect/bisect_step.py
utils/bisect/example.cfg

A config file determines the "good" and "bad" commits, and provides the paths to the MPAS code, the load script, etc.  It
also provides the commands for building the code, setting up the test case(s) and running them.
A driver script sets things up and makes the calls to `git bisect`, passing along the `utils/bisect/bisect_step.py` script for running each step of the bisection.
The `utils/bisect/bisect_step.py` script updates and builds the MPAS code, then sets up the compass test case(s) and runs compass.

Add scripts for using `git bisect`

---

compass/job/__init__.py

This prefix makes things harder to find and tab complete, and doesn't add any clarity since it is always obvious that each job script is a compass job script.

Drop compass_ prefix from job script names

---

compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
compass/ocean/tests/global_ocean/metadata.py

In the date stamp in output files and metadata, it is significantly less ambiguous to have a 4-digit year.

Switch from 2- to 4-digit year in global ocean

---

compass/landice/tests/koge_bugt_s/mesh.py

Nearly the smallest possible PR: a two character spelling typo in a logging string.

spelling typo

---

compass/ocean/tests/global_ocean/files_for_e3sm/diagnostics_files.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/make_diagnostics_files/__init__.py
conda/compass_env/spec-file.template
conda/recipe/meta.yaml
setup.py

MPAS-Analysis now supports 5 more projection comparison grids, and we want to generate the associated mapping files for each new MPAS-Ocean and -Seaice mesh.
For now, 2 functions have largely been copied from MPAS-Analysis. In the near future, it would be best to handle these in a better way.

Add more projection grids to diagnostics_files

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/initial_state.py
compass/ocean/tests/isomip_plus/ocean_test/__init__.py
compass/ocean/tests/isomip_plus/viz/plot.py
compass/ocean/vertical/__init__.py
compass/ocean/vertical/sigma.py

This merge also adds ISOMIP+ test cases that demonstrate the usage of the coordinate.
In the process, a small bug was found in the ISOMIP+ visualization in which the colormap bounds were incorrectly including zero even for fields (like salinity) where this is not appropriate.  This has also been fixed here for convenience.

Add a sigma vertical coordinate to ocean framework

---

compass/machines/pm-cpu.cfg
compass/parallel.py
compass/run/serial.py
compass/version.py
conda/albany_supported.txt
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml
docs/developers_guide/machines/index.rst
docs/developers_guide/machines/perlmutter.rst
docs/users_guide/machines/index.rst
docs/users_guide/machines/perlmutter.rst
docs/users_guide/quick_start.rst
utils/matrix/setup_matrix.py

This requires updating to mache 1.8.0 and bumping compass to 1.2.0-alpha.2.
Albany is not yet working, see: https://github.com/E3SM-Project/spack/issues/6

Add support for perlmutter CPU nodes

---

compass/namelist.py

Prior to this commit, if namelist options specified in test cases are out of date with the registry, the user is not warned. This PR adds a warning which is printed at the setup stage.

Add error message for namelist replacements

---

conda/bootstrap.py
conda/compass_env/spec-file.template
conda/otps/ci/linux.yaml
conda/otps/ci/osx.yaml
conda/otps/recipe/build.sh
conda/otps/recipe/meta.yaml
conda/recipe/meta.yaml

This merge also adds the resulting `otps` conda package as a dependency.
`otps` is needed for #456

Add a recipe for OSU tidal prediction software

---

compass/machines/chrysalis.cfg

This is what E3SM uses and we have had a lot of bit-for-bit failures with Intel-MPI (see #461) that might be better with OpenMPI.

Switch Chrysalis Intel to use OpenMPI by default

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/geom.py
compass/ocean/tests/isomip_plus/initial_state.py
compass/ocean/tests/isomip_plus/isomip_plus_test.py
compass/ocean/tests/isomip_plus/namelist.thin_film.forward_and_ssh_adjust
compass/ocean/tests/isomip_plus/ocean_test/__init__.py
compass/ocean/tests/isomip_plus/ssh_adjustment.py
compass/ocean/tests/isomip_plus/streamfunction.py
compass/ocean/tests/isomip_plus/viz/__init__.py
compass/ocean/tests/isomip_plus/viz/plot.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/isomip_plus.rst

This is just a clean-up PR to take care of a few things that have been missed over time in the ISOMIP+ test group.
* Rename `OceanTest` to `IsomipPlusTest` and move it from its own package directory to a module
* Some PEP8 issues
* Some parameters and attributes missing from docstrings
* Some plots that look weird for "normal" (z-star, no thin film) test cases.

Clean up ISOMIP+

---

compass/mesh/mesh.cfg
compass/mesh/spherical.py
compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/high_res_region.geojson
compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
compass/ocean/tests/global_ocean/mesh/wc14/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg

This merge also cleans up a doc string and switches the CMIP mesh for both SO12to60 and WC14 to the 1 degree, consistent with conversations with colleagues.

Add SO12to60E2r5 (without ice-shelf cavities)

---

compass/ocean/tests/hurricane/init/interpolate_atm_forcing.py

This PR fixes a typo in plotting the atmospheric forcing in the init step of the hurricane case.

Fix typo in hurrincane init plotting

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

We aren't yet ready for new features in shapley 2.0.0
See https://shapely.readthedocs.io/en/stable/migration.html for details.

Constrain shapely

---

compass/ocean/tests/dam_break/default/__init__.py
compass/ocean/tests/dam_break/namelist.forward
compass/ocean/tests/dam_break/streams.init

In order to avoid crashes of the dam break test case, tracers need to be initialized  (currently handled in init mode and fixed here https://github.com/E3SM-Ocean-Discussion/E3SM/pull/33), and those tracers also need to be stored in the initial state stream (fixed here). 
Related changes also included here are (1) adding the validation step to the test case and (2) disabling tracer tendencies, which are not needed in this test case.

Bugfix for dam break tests

---

compass/provenance.py

Some test cases don't need an MPAS component to be built in order to run.  This merge makes it so provenance does not attempt to get a git has for the MPAS component if the path to the component doesn't exist (presumably because the submodule has not been initialized).
Checklist

Fix provenance when E3SM submodule not needed

---

utils/e3sm_update/test_e3sm_changes.py

This merge updates the E3SM-Project submodule from [569ed6b730](https://github.com/E3SM-Project/E3SM/tree/569ed6b730) to [0273cfad9d](https://github.com/E3SM-Project/E3SM/tree/0273cfad9d).
This update includes the following MPAS-Ocean and MPAS-Frameworks PRs (check mark indicates bit-for-bit with previous PR in the list using the `pr` test suite on Chrysalis with Intel and OpenMPI, optimized):
-  As documented in the PR, 18 test cases fail baseline comparison but changes are small and expected. Before this, 2 decomposition test cases consistently fail.  After this PR, they pass again.
Checklist

Update E3SM-Project submodule

---

compass/ocean/tests/tides/init/streams.init

This addresses errors in the tides initial_state step related to an unused critical_passages stream. 
Checklist
Fixes #483

Remove critical passages stream for tides init

---

compass/ocean/tests/global_convergence/cosine_bell/__init__.py
compass/ocean/tests/global_convergence/cosine_bell/forward.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/init/__init__.py
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
compass/ocean/tests/hurricane/forward/__init__.py
compass/ocean/tests/hurricane/forward/forward.py
compass/ocean/tests/hurricane/init/__init__.py
compass/ocean/tests/hurricane/init/initial_state.py
compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/isomip_plus/isomip_plus_test.py
compass/ocean/tests/isomip_plus/ssh_adjustment.py
compass/ocean/tests/planar_convergence/conv_test_case.py
compass/ocean/tests/planar_convergence/forward.py
compass/ocean/tests/sphere_transport/correlated_tracers_2d/__init__.py
compass/ocean/tests/sphere_transport/correlated_tracers_2d/forward.py
compass/ocean/tests/sphere_transport/correlated_tracers_2d/namelist.forward
compass/ocean/tests/sphere_transport/divergent_2d/__init__.py
compass/ocean/tests/sphere_transport/divergent_2d/forward.py
compass/ocean/tests/sphere_transport/divergent_2d/namelist.forward
compass/ocean/tests/sphere_transport/nondivergent_2d/__init__.py
compass/ocean/tests/sphere_transport/nondivergent_2d/forward.py
compass/ocean/tests/sphere_transport/nondivergent_2d/namelist.forward
compass/ocean/tests/sphere_transport/rotation_2d/__init__.py
compass/ocean/tests/sphere_transport/rotation_2d/forward.py
compass/ocean/tests/sphere_transport/rotation_2d/namelist.forward
compass/ocean/tests/tides/forward/forward.py
compass/ocean/tests/tides/init/initial_state.py
compass/run/serial.py

This merge drops calls to `Testcase.run()` and instead override `step.constrain_resources()` in individual steps.
We have deprecated `Testcase.run()` because its use is not compatible with the task parallelism approach we (@altheaden and I) are developing.  Instead, the individual steps in a test case that need to set the number of tasks or cpus per task should override `constrain_resources()`, set `self.ntasks`, `self.min_tasks`, etc., and then call `super().constrian_resources()`.
In the near future (again related to task parallelism), it will also be useful to override `step.runtime_setup()` for tasks like creating graph partitions before running an MPAS component.  In anticipation of this change and to be consistent with the deprecation warning about `Testcase.run()`, this merge adds …

Override `constrain_resources()` in individual steps

---

compass/landice/tests/ismip6_forcing/ocean_thermal/process_thermal_forcing.py

This PR address the issue created by @trhille (https://github.com/MPAS-Dev/compass/issues/463) on having the `xtime` variable in the processed ocean climatology thermal forcing file in the `ismip6_forcing` landice test group. 
closes #463

Remove xtime variable from ocean climatology

---

compass/landice/tests/ismip6_forcing/atmosphere/process_smb.py

This PR adds an option to process 4km ISMIP6 atmosphere forcing files in the `ismip6_forcing` test group.

Add an option to process 4-km resolution forcing files

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

New versions are needed to support shapely >=2.0
The only code in compass itself that uses shapely is for generating MISOMIP output from the `isomip_plus` test cases.  As this is rarely used, a considerable amount of work to test, and the calls did not look likely to be affected by the change in shapely, I will not test that part of the code here.
Checklist

Update shapely, geometric_features and mpas_tools

---

compass/ocean/tests/isomip_plus/initial_state.py
compass/ocean/tests/isomip_plus/viz/plot.py

We need `landIceFraciton` to be zero when `landIceMask` is zero.
Following up on #469, but this is a bug and is non-BFB.

Fix `landIceFraction` in ISOMIP+

---

conda/bootstrap.py

Replace deprecated `importlib.resources.path()` call

---

compass/version.py
conda/albany_supported.txt
conda/bootstrap.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml
conda/unsupported.txt
docs/developers_guide/machines/cori.rst
docs/developers_guide/machines/index.rst
docs/developers_guide/machines/perlmutter.rst
docs/users_guide/machines/anvil.rst
docs/users_guide/machines/cori.rst
docs/users_guide/machines/perlmutter.rst
utils/matrix/setup_matrix.py

Checklist
Spack builds tested:

Update to compass v1.2.0-alpha.4 and mache v1.10.0 

---

compass/ocean/tests/isomip_plus/geom.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/isomip_plus.rst

Fix ISOMIP+ docs

---

compass/parallel.py

Omitting `-n 1` (as was done previously) means the step runs on all cores, not just 1.
Checklist
closes #507

Fix handling of ntasks = 1 for single node

---

conda/bootstrap.py
conda/compass_env/spec-file.template
conda/otps/ci/linux.yaml
conda/pnetcdf/ci/linux_mpi_mpich.yaml
conda/pnetcdf/ci/linux_mpi_openmpi.yaml
conda/pnetcdf/ci/osx_mpi_mpich.yaml
conda/pnetcdf/ci/osx_mpi_openmpi.yaml
conda/pnetcdf/recipe/build.sh
conda/pnetcdf/recipe/conda_build_config.yaml
conda/pnetcdf/recipe/meta.yaml
conda/scorpio/ci/linux_mpi_mpich.yaml
conda/scorpio/ci/linux_mpi_openmpi.yaml
conda/scorpio/ci/osx_mpi_mpich.yaml
conda/scorpio/ci/osx_mpi_openmpi.yaml
conda/scorpio/recipe/build.sh
conda/scorpio/recipe/conda_build_config.yaml
conda/scorpio/recipe/meta.yaml
conda/shared.py

This merge updates the conda packages for linux and osx to:
* `pnetcdf 1.12.3`
* `scorpio 1.4.1`
Checklist
A checkmark indicates that conda packages have been built, tested (with the ocean `nightly` suite) and uploaded for both `mpich` and `openmpi` variants:

Update conda pnetcdf and scorpio versions

---

conda/shared.py

The check for `.bashrc` or `.bash_profile` was looking in the current directory, not the home directory.
Checklist

Fix code for not adding mamba to .bashrc

---

docs/developers_guide/quick_start.rst

Add a short section describing pep8 to the developer's guide, quick start.
Checklist

Add pep8 guidance to docs

---

compass/landice/tests/circular_shelf/albany_input.yaml
compass/landice/tests/circular_shelf/circular_shelf.cfg
compass/landice/tests/circular_shelf/decomposition_test/__init__.py
compass/landice/tests/dome/albany_input.yaml
compass/landice/tests/greenland/albany_input.yaml
compass/landice/tests/greenland/albany_schoof_input.yaml
docs/users_guide/landice/test_groups/circular_shelf.rst

Albany is going to remove the support for Tet elements for MPAS generated meshes. 
In this PR we change all the land ice tests to use Wedge elements instead of Tet elements.
We also constrain the velocity on a patch of points, instead of on a single point, for the circular shelves test to remove the degree of freedom associated to rotations around the center of the shelf.
`Testing` perfomed on a linux machine linking the head of Albany master, as well as the branch of Albany where the Tets are disabled.
Checklist
@matthewhoffman  Let me know if this change requires an update to the documentation.

Use Wedge elements for all MALI tests

---

docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/index.rst
docs/developers_guide/ocean/test_groups/nonhydro.rst
docs/users_guide/machines/chicoma.rst
docs/users_guide/ocean/test_groups/index.rst

This merge also includes a fix to the Chicoma docs
Checklist

Fix nonhydro documentation

---

compass/ocean/rpe.py
compass/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
compass/ocean/tests/baroclinic_channel/rpe_test/__init__.py
compass/ocean/tests/baroclinic_channel/rpe_test/analysis.py
compass/ocean/tests/internal_wave/internal_wave.cfg
compass/ocean/tests/internal_wave/rpe_test/__init__.py
compass/ocean/tests/internal_wave/rpe_test/analysis.py
docs/users_guide/ocean/test_groups/baroclinic_channel.rst
docs/users_guide/ocean/test_groups/internal_wave.rst

This PR includes clean-up of the RPE test cases in the internal wave and baroclinic test groups. It fixes formatted strings and moves the list of viscosities to be tested to the config file.
Checklist

Cleanup ocean RPE tests

---

conda/bootstrap.py

This is necessary because the `nc-config` executable (and equivalents for the other libraries) cannot be used to locate the correct path for the libraries relative to the `bin` directory.
Checklist

Find netcdf and pnetcdf with env vars on Chicoma and PM

---

compass/landice/tests/humboldt/albany_input.yaml

Need to add `Use Pressurized Bed Above Sea Level: False` setting to albany_input.yaml for landice_humboldt_mesh-3km_restart_test_velo-fo_calving-von_mises_stress_damage-threshold_faceMelting test case to run, after https://github.com/sandialabs/Albany/pull/863
Checklist

Update albany_input.yaml with new basal pressure setting

---

compass/landice/tests/calving_dt_convergence/namelist.landice
compass/landice/tests/humboldt/decomposition_test/__init__.py
compass/landice/tests/humboldt/namelist.landice

This is necessary to prevent an error that occurs when config_calving = 'von_Mises_stress' and config_flowParamA_calculation = 'constant'
Checklist

Add config_flowParamA_calculation = 'PB1982' to namelists

---

compass/landice/mesh.py
compass/landice/tests/greenland/high_res_mesh/high_res_mesh.cfg
compass/landice/tests/greenland/mesh.py
compass/landice/tests/humboldt/humboldt.cfg
compass/landice/tests/humboldt/mesh.py
compass/landice/tests/kangerlussuaq/mesh.py
compass/landice/tests/kangerlussuaq/mesh_gen/mesh_gen.cfg

Add the option to include bed topography in the cell spacing function. This allows for high resolution for areas into which the grounding line may retreat, even if they are not fast-flowing or close to the margin. The user sets config options for what should be considered low and high bed topography, as well as the distance from the grounding line within which the bed topography should have an influence on cell spacing. Included in this PR are updates to the `greenland`, `humboldt`, and `kangerlussuaq` mesh generation test cases, which now use bed topography to determine cell spacing.
The cell spacing function for bed topography uses a logistics function to smoothly transition between high and low resolution over areas of low and high bed topography. That cell spacing is then modified …

Add bed topo to cell spacing

---

conda/bootstrap.py
conda/configure_compass_env.py
conda/shared.py

It turns out that the `boa` package isn't compatible with the latest `mamba`, but the latest `mamba` is needed in order to use the latest `conda`.  So when compass tries to update everything, things end in a bad state. (An error message relate to a missing `no_user` attribute occurs when running `mamba`.)
The solution seems to be not to include `boa` in the base environment for now.  This won't affect compass, since `boa` is used to build conda packages and was just there for convenience (I sometimes need to build conda packages for compass maintenance).
Checklist
closes #544

Fix deployment with latest conda (23.1.0)

---

compass/default.cfg
compass/ocean/tests/global_convergence/cosine_bell/forward.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
compass/ocean/tests/hurricane/forward/forward.py
compass/ocean/tests/hurricane/init/initial_state.py
compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/isomip_plus/ssh_adjustment.py
compass/ocean/tests/planar_convergence/forward.py
compass/ocean/tests/sphere_transport/correlated_tracers_2d/forward.py
compass/ocean/tests/sphere_transport/divergent_2d/forward.py
compass/ocean/tests/sphere_transport/nondivergent_2d/forward.py
compass/ocean/tests/sphere_transport/rotation_2d/forward.py
compass/ocean/tests/tides/forward/forward.py
compass/ocean/tests/tides/init/initial_state.py
compass/parallel.py
compass/run/serial.py
compass/step.py
docs/developers_guide/api.rst

If you are on a slurm system but a slurm job is not detected, you are assumed to be on a login node.  In that case, it is like being on a single node system, restricted to a small number of cores (set with the config option `login_cores = 4` in the `[parallel]` config section).  In addition, you are not allowed to run MPI jobs (steps with `ntasks` > 1).
This is enforced by modifying the `Step.constrain_resources()` method, which now takes a dictionary of `available_resources` rather than a single `available_cores` argument.  (Many tasks have their overridden `constrain_resources()` method changed as a result.)
The new, stricter linter required cleaning up some code in the process.
Checklist
closes #495

Allow test cases to run on login nodes

---

conda/bootstrap.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/shared.py

The `configure_compass_env.py` script now takes two flags, `--mache_fork` and `--mache_branch` that are used to clone the fork and branch locally, then install mache from it.  This saves the trouble of developers cloning it themselves and building the mache conda package.
This merge also simplifies the deployment scripts by requiring python3, which I believe all systems have available without loading any modules. This allows us to remove some awkward imports and to use f-strings instead of format commands.
This merge also removes the `cxx17` spack variant of Albany because this variant is no longer supported (Albany always uses the c++17 standard).
Checklist
changes look as expected
closes #520

Enable easier mache testing

---

docs/developers_guide/deploying_spack.rst
docs/developers_guide/quick_start.rst
docs/index.rst
docs/tutorials/dev_add_test_group.rst
docs/tutorials/dev_porting_legacy.rst
docs/users_guide/machines/index.rst
docs/users_guide/quick_start.rst

This merge adds a kind of tutorial about testing and deploying shared spack environments for compass.
It also includes some updates to the documentation where we recommend installing (or letting the `configure_compass_env.py` script install) Mambaforge instead of Miniconda3.  @matthewhoffman found by painful trial and error that there doesn't seem to be a way to cleanly install mamba in a new Miniconda3 installation.  (This is also something I've been struggling with on CI lately.)
Checklist

Add instructions for deploying spack

---

compass/ocean/tests/isomip_plus/streamfunction.py

The fix involves replacing NaNs in transport with zeros, so that the resulting sums are not themselves contaminated with NaNs.
This merge also contains some linting-related clean up.
Checklist

Fix `isomip_plus` streamfunction computation

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/cull_mesh.py
compass/ocean/tests/isomip_plus/files_for_e3sm.py
compass/ocean/tests/isomip_plus/geom.py
compass/ocean/tests/isomip_plus/initial_state.py
compass/ocean/tests/isomip_plus/isomip_plus.cfg
compass/ocean/tests/isomip_plus/isomip_plus_test.py
compass/ocean/tests/isomip_plus/misomip.py
compass/ocean/tests/isomip_plus/planar_mesh.py
compass/ocean/tests/isomip_plus/spherical_mesh.py
compass/ocean/tests/isomip_plus/streamfunction.py
compass/ocean/tests/isomip_plus/viz/plot.py

This merge builds on #469 and #470 to add support for meshes that are a patch of a sphere in ISOMIP+ test cases.
The idea is that these regional meshes on the sphere could be use to do idealized testing within E3SM.

Add support for spherical meshes in ISOMIP+

---

compass/ocean/suites/pr.txt
compass/ocean/tests/global_ocean/files_for_e3sm/graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py
compass/ocean/tests/global_ocean/global_ocean.cfg
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst

The old algorithm wasn't generating the breadth of partition sizes that the E3SM team needs.  The updated algorithm seems likely to generate nearly all of the partition sizes that could conceivably be useful for a given mesh.
Checklist

Update algorithm for core counts for MPAS partition files

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/files_for_e3sm_step.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_mesh.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_mesh.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/vertical/__init__.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

These also need to be added to `inputdata` in `shared/meshes/mpas`
This merge also makes public some functions from the `compass.ocean.vertical` module that are used to add `cellMask` and `zMid` variables to the MPAS-Ocean mesh.
Checklist
closes #569

Add `files_for_e3sm` steps for ocean and sea-ice meshes

---

compass/ocean/tests/global_ocean/__init__.py

This merge adds a helper function that is used to add test cases for each type of mesh.  This reduces code redundancy and makes it easier to make future changes.
Checklist

Simplify adding test cases to `global_ocean`

---

compass/landice/tests/circular_shelf/albany_input.yaml
compass/landice/tests/dome/albany_input.yaml
compass/landice/tests/ensemble_generator/thwaites/albany_input.yaml
compass/landice/tests/greenland/albany_input.yaml
compass/landice/tests/greenland/albany_schoof_input.yaml
compass/landice/tests/humboldt/albany_input.yaml
compass/landice/tests/mismipplus/albany_input.yaml
compass/landice/tests/thwaites/albany_input.yaml

This PR removes optional/unused preconditioners from landice test inputs that use Trilinos packages (Ifpack/ML) that we no longer use for our builds. Having these optional preconditioners cause invalid parameter exceptions when running landice tests using newest Albany builds. These tests don't use the Ifpack/ML preconditioners anyway so this won't change the behavior of these tests.
Checklist

Remove Ifpack and ML preconditioners from landice test inputs

---

docs/developers_guide/machines/chicoma.rst
docs/developers_guide/machines/perlmutter.rst
docs/users_guide/machines/chicoma.rst
docs/users_guide/machines/perlmutter.rst

These are specific to Chicoma and Perlmutter, where we have disabled hyperthreading by default.
Checklist

Add information on enabling hyperthreading to docs

---

compass/ocean/mesh/cull.py
compass/ocean/mesh/remap_topography.cfg
compass/ocean/mesh/remap_topography.py
compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/streams.topo
compass/ocean/tests/global_ocean/mesh/__init__.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/framework.rst
docs/users_guide/ocean/framework/index.rst
docs/users_guide/ocean/framework/mesh.rst

This merge adds a step for remapping bathymetry and ice-shelf topography to the ocean framework.  It also adds this step to the mesh test cases in `global_ocean`.  It updates the `cull_mesh` step to use the remapped bathymetry to determine the land mask if topography remapping was performed.  It updates most meshes to use the this new approach, leaving the QU240 and Icos240 meshes as they were for more efficient testing.  Finally, this merge modifies the topography output with the variable names expected in MPAS-Ocean init mode and creates a stream for reading them in.
An alteration is needed to MPAS-Ocean to bypass reading in the land-ice topography from a lon-lat file.  Such a bypass exists for the bathymetry but not for land-ice topography.
Needs: …

Add bathymetry remapping

---

conda/compass_env/spec-file.template

This is necessary for CI to pass.
Should be fixed in https://github.com/conda-forge/scikit-image-feedstock/pull/102

Don't allow version of scikit-image with bad dependencies

---

compass/ocean/mesh/cull.py

Some `cull_mesh` steps take a remapped topography as an input, while others do not (for added speed and to keep resources under control).  This merge fixes a bug in which the `cull_mesh` step was trying to cull the topogrpahy file even if none is present.
Checklist
closes #593

Only cull topography for cull_mesh steps that have it

---

compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg

It appears that 128 processes are too many and slow down the step significantly.
Checklist
closes #598

Reduce no. of processes for QU240 cull_mesh step

---

compass/ocean/suites/pr.txt
compass/ocean/tests/internal_wave/__init__.py
compass/ocean/tests/internal_wave/default/__init__.py
compass/ocean/tests/internal_wave/forward.py
compass/ocean/tests/internal_wave/rpe_test/__init__.py
compass/ocean/tests/internal_wave/viz.py
docs/developers_guide/ocean/test_groups/internal_wave.rst
docs/users_guide/ocean/test_groups/internal_wave.rst

Currently, there are no tests of the vertical Lagrangian remapping capability in compass. This PR adds a VLR version for the default and RPE tests of the internal wave test group.
Checklist

Add VLR test to internal wave case

---

compass/ocean/tests/tides/init/dem_pixel.py

Without this change, the test `ocean/tides/Icos7/init` fails. The error message says that  `np.bool` is no longer supported. With this change, the test case runs successfully on perlmutter using `load_dev_compass_1.2.0-alpha.4_pm-cpu_gnu_mpich.sh`.
The flake linter changed the order of the import lines.

Change np.bool to bool

---

compass/ocean/tests/baroclinic_channel/__init__.py

This PR adjusts the number of cells used in meshes for the baroclinic channel test case to ensure the 'standard' 160x500km domain is defined. Previously, the channel has had a shorter y-length of sqrt(3)/2 * 500 => 433km.
- When using the `make_planar_hex_mesh` routine, the number of cells along the y-axis should be scaled by `2/sqrt(3)` to account for hexagonal geometry.
The channel is a standard community test case, and use of the 160x500km domain enables model intercomparison, e.g.:
- Ilıcak, M., Adcroft, A.J., Griffies, S.M. and Hallberg, R.W., 2012. Spurious dianeutral mixing and the role of momentum closure. Ocean Modelling, 45, pp.37-58.
- Petersen, M.R., Jacobsen, D.W., Ringler, T.D., Hecht, M.W. and Maltrud, M.E., 2015. Evaluation of the arbitrary Lagrangian–Eulerian vertical …

Adjust #cells in baroclinic channel to define 160x500km domain

---

compass/step.py

The code for changing permissions was being given an incorrect directory and then was failing silently.  This merge fixes the path and also removes the silent failure (an error will be raised if the status of the download directory cannot be determined).
This merge also adds the database root and the root for each affected core to the list of directories to chmod/chown anytime any files get downloaded.
Checklist
closes #586 
closes #608

Fix bug in changing permissions on downloaded files

---

compass/ocean/__init__.py
compass/ocean/tests/utility/__init__.py
compass/ocean/tests/utility/extrap_woa/__init__.py
compass/ocean/tests/utility/extrap_woa/combine.py
compass/ocean/tests/utility/extrap_woa/extrap_step.py
compass/ocean/tests/utility/extrap_woa/extrap_woa.cfg
compass/ocean/tests/utility/extrap_woa/remap_topography.py
conda/compass_env/spec-file.template
conda/recipe/meta.yaml
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/framework.rst
docs/developers_guide/ocean/test_groups/index.rst
docs/developers_guide/ocean/test_groups/utility.rst
docs/users_guide/ocean/test_groups/index.rst
docs/users_guide/ocean/test_groups/utility.rst
setup.py

This merge adds a new `utility` test group mostly for provenance and ease of updating data sets in the future.
For now, the only test case is `ExtrapWoa`, used to extrapolate WOA 2023 data into ice-shelf cavities and ice shelves, then into grounded ice, land and below bathymetry.
To convert from in situ to potential temperature, the `gsw` package has been added as a compass dependency.
Checklist

Add a test case for extrapolating WOA 2023 data

---

compass/ocean/tests/global_ocean/mesh/__init__.py

The config parser can behave strangely when config options are set, then config files are loaded from other files, then more config options are set.  We now set all config options in the mesh test case only after loading config files that we want overwrite.
Checklist
closes #612

Fix wISC in mesh prefix

---

compass/ocean/tests/global_ocean/files_for_e3sm/ocean_mesh.py

This likely got missed because `ocean_mesh` got added to `files_for_e3sm` since the floating variable branch was created (several months ago).
Checklist

Add land-ice floating variables to `ocean_mesh` step

---

compass/ocean/tests/global_ocean/mesh/arrm10to60/arrm10to60.cfg
compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg
compass/ocean/tests/global_ocean/mesh/kuroshio/kuroshio.cfg
compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg
compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg
compass/ocean/tests/global_ocean/metadata.py
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/config_files.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

We need a different placeholder in config options for situations where we need to replace them (not using extended interpolation in the config file) at runtime.  Currently, this only applies to `levels`, the number of vertical levels but it could apply to `creation_date` and `bottom_depth` so we support these in the same way.
Checklist
closes #614

Fix substitution of `levels` at runtime in `global_ocean`

---

compass/ocean/tests/dam_break/namelist.forward
compass/ocean/tests/drying_slope/namelist.forward

This PR sets `config_use_debugTracers=.false.` for all `dam_break` and `drying_slope` tests. This isn't strictly necessary for the multi-layer cases but there is no need to use `debugTracers` in any of these cases.

Fixup namelists for single layer RK4 ocean tests

---

compass/ocean/tests/global_ocean/mesh/arrm10to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/kuroshio/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/__init__.py

In python, string flag specifications require both single and double quotes. This fixes the recent `config_implicit_bottom_drag_type` addition. This broke all the `dynamic_adjustment` cases, and specifically `ocean/global_ocean/QU240/WOA23/dynamic_adjustment` in the `pr` suite. This works now.

Add double quotes to flag

---

compass/ocean/tests/global_ocean/init/initial_state.py

The namelist option `config_global_ocean_land_ice_topo_source` doesn't exist.  Instead, `config_global_ocean_topography_source` is used both for bathymetry and land-ice topography.
This seems to have got missed in #566.
Checklist

Remove unused namelist option

---

compass/parallel.py

We want to explicitly specify how many nodes to use in `srun` calls for slurm steps because otherwise we may end up with a job running on more nodes than needed and an incompatible PIO task count.
Checklist
closes #629

Explicitly specify nodes in srun calls

---

compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
compass/ocean/tests/global_ocean/mesh/arrm10to60/arrm10to60.cfg
compass/ocean/tests/global_ocean/mesh/arrm10to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/ec30to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg
compass/ocean/tests/global_ocean/mesh/kuroshio/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/kuroshio/kuroshio.cfg
compass/ocean/tests/global_ocean/mesh/kuroshio12to60/kuroshio12to60.cfg
compass/ocean/tests/global_ocean/mesh/kuroshio8to60/kuroshio8to60.cfg
compass/ocean/tests/global_ocean/mesh/qu240/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu240/qu240.cfg
compass/ocean/tests/global_ocean/mesh/so12to60/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/so12to60/so12to60.cfg
compass/ocean/tests/global_ocean/mesh/wc14/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/wc14/wc14.cfg
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/tasks.py
compass/step.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

This merge switches many global ocean steps to getting the core count from either an estimate or exact number of cells in the mesh.  Similarly, it switches to computing the time steps (both barotropic and baroclinic) from the minimum resolution of the mesh.
This work paves the way for generalized QU and icosahedral global ocean meshes.
Checklist

Get global ocean resources and time steps based on mesh size

---

compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/mesh/qu/__init__.py
compass/ocean/tests/global_ocean/mesh/qu/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/mesh/qu/dynamic_adjustment/streams.template
compass/ocean/tests/global_ocean/mesh/qu/icos.cfg
compass/ocean/tests/global_ocean/mesh/qu/namelist.split_explicit
compass/ocean/tests/global_ocean/mesh/qu/qu.cfg
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

A user can set the resolution at setup or runtime with the `qu_resolution` config option in the `global_ocean` section.
Checklist

Add general QU and Icos meshes

---

compass/ocean/tests/global_ocean/files_for_e3sm/graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_mesh.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py

These include multiples of the node sizes up to 20 nodes for all node sizes supported by E3SM.  They also include any core count that is an exact multiple of a supported node size that is within 2 nodes of a set of desirable set of core counts for the ne30 atmosphere/land mesh (factors of 5400).
This merge also takes care of some issues exposed while generating new partition files:
* some existing ocean meshes with ice-shelf cavities don't have the `landIceDraft` variable, so we simply skip it when generating an ocean mesh if it is not present.
* some meshes *do* contain a `cullCell` variable, which causes trouble for the sea-ice partitioning tools, so we remove that variable before passing the mesh to the sea-ice partition tools.
Checklist
closes #627

Add more graph partition sizes

---

compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/mesh/__init__.py

We use an older, lower resolution data set for the QU240 meshes.
This work is a preliminary step that will allow us to move toward initializing the global ocean in python, rather than Fortran.  
Checklist

Always remap topogrpahy, even for low res meshes

---

compass/ocean/mesh/remap_topography.cfg
compass/ocean/mesh/remap_topography.py
compass/ocean/tests/global_ocean/init/namelist.init

A bug in #566 left the remapped topography multiplied by the remapped ocean mask.  This means that the topography falls back to zero at coastlines and grounding lines under ice shelves.  This merge fixes that issue by renormalizing topography as long as the remapped ocean mask is over a given threshold (0.01 by default).
This merge also turns off smoothing of topography in `global_ocean` init mode because it should no longer be needed with the conservative remapping approach.
Checklist

Renormalize topography after remapping in `global_ocean`

---

compass/ocean/tests/global_ocean/files_for_e3sm/graph_partition.py

The algorithm for computing graph partition sizes was previously producing partitions that were larger than the number of cells in the mesh.  With this fix, there will not be fewer than about 2 cells per task.
Checklist

Bound graph partition sizes

---

compass/ocean/tests/global_ocean/files_for_e3sm/graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py

This applies to meshes with fewer than 30,000 cells.  Although MPAS components run in standalone don't require partition files for a single core, E3SM does need them.
Checklist

For smaller meshes, create partitions for a single task

---

compass/ocean/suites/ecwisc30to60.txt
compass/ocean/suites/quwisc240.txt
compass/ocean/suites/quwisc240_for_e3sm.txt
compass/ocean/suites/sowisc12to60.txt
compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/data_ice_shelf_melt/__init__.py
compass/ocean/tests/global_ocean/data_ice_shelf_melt/namelist.forward
compass/ocean/tests/global_ocean/data_ice_shelf_melt/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/data_ice_shelf_melt/streams.forward
compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
conda/compass_env/spec-file.template
conda/recipe/meta.yaml
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst
setup.py

This merge also adds a step for staging the remapped melt fluxes in the appropriate directory for use in E3SM.  It can be used to compute data melt fluxes for existing meshes.
Checklist

Add a global ocean test case for computing and running with data (prescribed) melt rates

---

compass/landice/mesh.py
compass/landice/tests/antarctica/mesh.py
compass/landice/tests/antarctica/mesh_gen/__init__.py
compass/landice/tests/greenland/mesh.py
compass/landice/tests/greenland/mesh_gen/__init__.py
compass/landice/tests/humboldt/mesh.py
compass/landice/tests/humboldt/mesh_gen/__init__.py
compass/landice/tests/kangerlussuaq/mesh.py
compass/landice/tests/kangerlussuaq/mesh_gen/__init__.py
compass/landice/tests/koge_bugt_s/mesh.py
compass/landice/tests/koge_bugt_s/mesh_gen/__init__.py
compass/landice/tests/thwaites/mesh.py
compass/landice/tests/thwaites/mesh_gen/__init__.py

Instead of using `MpasMaskCreator.x`, use the python command-line tool `compute_mpas_region_masks`.
This merge also updates several mesh creation steps to use up to 128 cores for making masks.
Finally, this merge adds validation of 4 mesh variables against a baseline for each `MeshGen` test case.  This is used to show that the results are BFB with the main branch.
Checklist

Switch to python masking for culling landice meshes

---

compass/landice/tests/circular_shelf/decomposition_test/__init__.py

This is required to allow circular shelf decomposition test to pass after updating version of Albany in #641.  The differences are expected.  Closes #654 .
Checklist

Update tolerance on circ shelf decomp test

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This brings in the NetCDF-C version of the mesh conversion tools and the capability to sort mesh indices for better performance as well as bug fixes related to widening transects and computing the MOC southern transect.
Checklist

Update to MPAS-Tools v0.22.0

---

compass/ocean/mesh/cull.py

We need to create the graph file only after sorting has happened.
Checklist

Sort mesh indices before saving culled global ocean meshes

---

compass/ocean/iceshelf.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/ssh_adjustment.py
docs/developers_guide/machines/index.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

This merge contains various changes to the `global_ocean` test group that are needed to support large meshes like the RRS6to18 in #576.
Checklist

Clean up global ocean test group for large meshes

---

conda/bootstrap.py
conda/compass_env/spec-file.template
conda/shared.py

This merge also sets a flag to indicate that we don't have ADIOS on unsupported machines.
This merge also stops removing the `boa` conda package, which is no longer causing the issues reported in #544 
Checklist
closes #664

Update conda packages for unsupported machines

---

compass/ocean/tests/hurricane/lts/forward/namelist.ocean
compass/ocean/tests/hurricane/lts/forward/streams.ocean

Made minor changes to the streams and namelist of the hurricane lts test case.
The change to the streams is to print pointwise stats and output with the same frequency as the standard hurricane test. The change to namelist is to run for the same duration as the standard hurricane test.
Checklist

Minor changes to lts forward nmlist and streams

---

compass/model.py

Before this fix, we were seeing `culled_graph.info` files like:
```
7435 21369.0
8 3 2
1 7 9 8
...
```
The number of edges was being converted to a float because of a non-integer division by 2.
Checklist

Fix nEdges float --> int in graph files

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This brings in a bug fix where mask variables are cast to type int32 before they are passed to the `cull()` method, a requirement of the new `MpasCellCuller.x`, which does not support int64 or float mask.
Checklist

Update to `mpas_tools` 0.23.0

---

compass/ocean/tests/global_ocean/data_ice_shelf_melt/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py

This merge:
* adds a missing `Time` dimension to the ice shelf melt flux variables if one is not already present.
* fixes as issue where the step for remapping data ice shelf melt fluxes was being skipped in `files_for_e3sm` for existing meshes
It also removes the `landIceFluxMask` variable from the DISMF output file because this variable is not used and could cause confusion.
Checklist

Two fixes to data ice shelf melt fluxes

---

compass/ocean/tests/drying_slope/__init__.py
compass/ocean/tests/drying_slope/loglaw/__init__.py
compass/ocean/tests/drying_slope/namelist.single_layer.forward
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/drying_slope.rst
docs/users_guide/ocean/test_groups/drying_slope.rst

This PR adds 4 ocean `drying_slope` tests (2 resolutions and 2 vertical coordinates) which exercise the log-law version of implicit bottom drag. This bottom drag option is introduced by https://github.com/E3SM-Project/E3SM/pull/5734.
Checklist

Add a test for log-law ocean bottom drag

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py
conda/compass_env/spec-file.template
conda/recipe/meta.yaml
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst

This is used in E3SM runs with data iceberg freshwater fluxes.
Checklist

Add a step for remapping iceberg climatologies 

---

compass/landice/tests/enthalpy_benchmark/A/namelist.landice1
compass/landice/tests/enthalpy_benchmark/A/namelist.landice2
compass/landice/tests/enthalpy_benchmark/A/namelist.landice3
compass/landice/tests/enthalpy_benchmark/namelist.landice
compass/landice/tests/hydro_radial/namelist.landice
compass/landice/tests/hydro_radial/restart_test/namelist.full
compass/landice/tests/hydro_radial/restart_test/namelist.restart
compass/landice/tests/hydro_radial/restart_test/namelist.restart.rst
compass/landice/tests/hydro_radial/spinup_test/namelist.landice

MALI's Registry has been using a default `config_start_time` of '0000-01-01_00:00:00', which is not CF-compliant.  The MALI-Dev PR https://github.com/MALI-Dev/E3SM/pull/85 updates Registry to make the default `config_start_time` '0001-01-01_00:00:00'.  This PR updates the few compass tests that were assuming a start year of 0000.
Checklist

Update tests to support start year of 0001

---

conda/compass_env/spec-file.template
conda/recipe/meta.yaml

This brings in 2 new critical land blockages to make sure the interior of Greenland does not become part of the ocean (because of the GEBCO topography that we use).
Checklist

Update to geometric_features 1.3.0

---

compass/ocean/iceshelf.py
compass/ocean/tests/ice_shelf_2d/__init__.py
compass/ocean/tests/ice_shelf_2d/default/__init__.py
compass/ocean/tests/ice_shelf_2d/forward.py
compass/ocean/tests/ice_shelf_2d/ice_shelf_2d.cfg
compass/ocean/tests/ice_shelf_2d/initial_state.py
compass/ocean/tests/ice_shelf_2d/namelist.forward
compass/ocean/tests/ice_shelf_2d/namelist.single_layer.forward_and_ssh_adjust
compass/ocean/tests/ice_shelf_2d/namelist.tidal_forcing.forward
compass/ocean/tests/ice_shelf_2d/restart_test/__init__.py
compass/ocean/tests/ice_shelf_2d/ssh_adjustment.py
compass/ocean/tests/ice_shelf_2d/streams.forward
compass/ocean/tests/ice_shelf_2d/viz.py
compass/ocean/tests/isomip_plus/viz/plot.py

This PR adds new `ice_shelf_2d` test cases which are combinations of:
* `2km` resolution
* `single_layer` vertical coordinate
* `tidal_forcing` version of the default test case
There are also changes made to the cfg options related to the cavity geometry which I think are more intuitive for users looking to modify the cavity geometry. In addition, the `isomip_plus` plotter class was imported to generate new plots.
Checklist

Add additional ice_shelf_2d test cases

---

compass/ocean/iceshelf.py
compass/ocean/mesh/cull.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/mesh/rrs6to18/rrs6to18.cfg

We will do this for large meshes like RRS6to18 for better performance.
This merge also fixes an `ncks` call for converting to CDF5 format but overwriting the file if it already exists.
Checklist

Allow culled mesh to be converted to CDF-5 format

---

compass/ocean/tests/global_ocean/mesh/ec30to60/ec30to60.cfg

Long name: ECwISC30to60L64E3SMv3r2
As with previous versions of the mesh, this Eddy Closure (EC) mesh has:
* 30 km resolution at the equator
* 60 km resolution at mid latitudes
* 35 km resolution near the poles
Mesh, initial condition, dynamic adjustment and files for E3SM are on Chrysalis at:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/e3smv3-meshes/ecwisc30to60e3r2
```
Checklist
Replaces #666

New Mesh: ECwISC30to60E3r2

---

compass/ocean/tests/global_ocean/mesh/qu/qu.cfg

Long name: IcoswISC30L64E3SMv3r2
This Icosahedral (Icos) mesh is made by subdividing an icosahedron and has nearly uniform 30 km resolution.
Mesh, initial condition, dynamic adjustment and files for E3SM are on Chrysalis at:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/e3smv3-meshes/icoswisc30e3r2
```
Checklist

New Mesh: IcoswISC30E3r2

---

compass/ocean/tests/isomip_plus/__init__.py
compass/ocean/tests/isomip_plus/files_for_e3sm.py
compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/isomip_plus/isomip_plus.cfg
compass/ocean/tests/isomip_plus/isomip_plus_test.py
compass/ocean/tests/isomip_plus/namelist.tidal_forcing.forward
compass/ocean/tests/isomip_plus/ssh_adjustment.py
compass/ocean/tests/isomip_plus/viz/__init__.py

This PR adds additional test cases with tidal forcing and a thin film for testing of the wetting and drying capability (i.e., grounding line motion). No changes to the documentation are needed. These tests are not added to the `wetdry` test suite; further testing of the wetting and drying scheme are needed to determine which `isomip_plus` tests are best suited for this purpose.

Add a few isomip_plus configurations for wetting and drying

---

compass/ocean/mesh/remap_topography.py
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostic_maps.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py
conda/compass_env/spec-file.template

Update to pyremap 1.1.0

---

compass/ocean/mesh/remap_topography.py
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostic_maps.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py
conda/compass_env/spec-file.template

I changed my mind about #698.  We should not make this change until after the E3SM v3 meshes are done because we risk having meshes without ice-shelf cavities not matching meshes with them.
I will revive #698 once we're done with E3SM v3 meshes.  For now, we will stick with pyremap 1.0.1.

Use pyremap 1.0.1

---

compass/ocean/tests/isomip_plus/viz/plot.py

We need to make what was an argument to `Polygon` before a keyword argument `closed=True` for compatibility with more recent versions of matplotlib.
Checklist

Fix ISOMIP+ plotting

---

compass/ocean/tests/global_ocean/dynamic_adjustment/__init__.py

As discussed in https://github.com/python/cpython/issues/57514, there are discrepancies in the time parsing libraries on different systems.  This PR attempts to find a solution that works on OSX as well as the Linux systems we usually use.
Checklist

Fix dynamic adjustment time parsing for OSX

---

conda/compass_env/load_compass.template
conda/shared.py

There is an issue where the latest mamba isn't compatible with the latest conda but locally cached versions of the mamba package don't know this.  The mamba package has been patched to a reinstall will fix teh issue. This should be fixed more permanently in mamba 1.5.2, which should be released soon.
Checklist

Temporary fix to reinstall mamba=1.5.1

---

compass/ocean/suites/wetdry.txt
compass/ocean/tests/drying_slope/__init__.py
compass/ocean/tests/drying_slope/decomp/__init__.py
compass/ocean/tests/drying_slope/streams.forward
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/drying_slope.rst
docs/users_guide/ocean/test_groups/drying_slope.rst

This PR adds a decomp test case to the drying slope test group.
Checklist
This test case helps evaluate https://github.com/MPAS-Dev/compass/issues/686.

Add decomp test case to the drying slope test group

---

compass/config.py

We don't want to do this for config options that start with other config options.
Backport of https://github.com/E3SM-Project/polaris/pull/136
Checklist

Fix conversion to absolute paths in config files

---

conda/shared.py

A temporary constraint on conda and mamba is no longer needed, now that `mamba` 1.5.2 is available and compatible with the latest `conda`.

Remove temporary fix for mamba 1.5.1

---

compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py

`bergFreshWaterFluxData` --> `bergFreshwaterFluxData`
Checklist

Fix variable name in iceberg climatologies

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/files_for_e3sm_step.py
compass/ocean/tests/global_ocean/files_for_e3sm/write_coeffs_reconstruct/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/write_coeffs_reconstruct/namelist.reconstruct
compass/ocean/tests/global_ocean/files_for_e3sm/write_coeffs_reconstruct/streams.reconstruct
compass/ocean/tests/global_ocean/forward.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst

Add step for reconstruction coeffs

---

compass/ocean/tests/hurricane/configure.py
compass/ocean/tests/hurricane/hurricane.cfg

This PR fixes this error:
> configparser.NoOptionError: No option 'convert_culled_mesh_to_cdf5' in section: 'spherical_mesh'
when running the cull mesh step for the`mesh_lts` hurricane test case.
Checklist
closes #725

Fixed issue with convert_culled_mesh_to_cdf5 for hurricane test case

---

compass/landice/mesh.py

This reverts commit 8b327bd224c27d3590e247002588469544701c51, which inadvertently broke the `landice/antarctica/mesh_gen` case and could lead to unexpected behavior elsewhere.
Checklist
This closes https://github.com/MPAS-Dev/compass/issues/729.

Fix `landice/antarctica/mesh_gen`

---

.github/workflows/build_workflow.yml
conda/compass_env/spec-file.template

This is needed for compatibility with the MPAS-Tools update in #718.
This merge drops the `--env_only` flag in GitHub Actions in the hopes that this will catch this kind of issue in the future.
Checklist

Update conda `parallelio` to 2.6.2

---

compass/ocean/mesh/cull.py

Before this fix, cells that were more than half land according to the remapped topography dataset but had been included in the ocean (through critical passages) were mistakenly being categorized as land ice simply because they were "not ocean".
With this fix, the `landIceMask` is computed based on where the `landIceFracObserved` from the remapped topography dataset is greater than 0.5.  A new function is needed to compute this mask because this definition is not the same as the mask used to cull the mesh when ice-shelf cavities are excluded from the ocean domain.
Checklist

Fix a bug in how `landIceMask` is computed

---

compass/version.py
conda/bootstrap.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/default.cfg
conda/recipe/meta.yaml

This merge also updates mache to 1.17.0, which updates support for Chicoma.
Checklist
MPAS-Ocean with `pr`:
MALI with `full_integration`:
MPAS-Ocean with `nonhydro` - warnings about namelist options reported in #712:

Update to 1.2.0-alpha.7

---

compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/smooth_topo.template
compass/ocean/tests/global_ocean/mesh/qu/dynamic_adjustment.yaml
compass/ocean/tests/global_ocean/mesh/qu/qu.cfg
compass/ocean/tests/global_ocean/streams.forward

Long name: IcoswISC30L64E3SMv3r5
This nearly uniform 30 km mesh is the dual mesh of a subdivided icosahedron (Icos).
This mesh differs from IcoswISC30E3r2 (#691) primarily in having the the bug fix in #732, but also it has been produced with updated versions of the `mpas_tools` and `pyremap` packages, leading to small changes in the topography and coast line.
It differs from IcoswISC30E3r4 (#734) in not having additional topographic smoothing.
Mesh, initial condition, dynamic adjustment and files for E3SM are on Chrysalis at:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/e3smv3-meshes/icoswisc30e3r5
```
Checklist

New Mesh: IcoswISC30E3r5

---

.github/workflows/build_workflow.yml
.github/workflows/docs_workflow.yml
conda/bootstrap.py
conda/compass_env/load_compass.template
conda/configure_compass_env.py
conda/shared.py
docs/developers_guide/deploying_spack.rst
docs/developers_guide/ocean/test_groups/drying_slope.rst
docs/developers_guide/quick_start.rst
docs/tutorials/dev_add_rrm.rst
docs/tutorials/dev_add_test_group.rst
docs/tutorials/dev_porting_legacy.rst
docs/users_guide/machines/index.rst
docs/users_guide/quick_start.rst
utils/e3sm_update/README.md

Yet again, I ran into problems with the `mamba` command today.  It seems it is time to abandon it and return to the `conda` command instead (along with the `libmamba` solver).
Checklist

Remove mamba commands and switch to Miniforge

---

docs/developers_guide/building_docs.rst

This merge adds information about how to view compiled documentation via NERSC's web Science Gateway to avoid needing to scp the compiled documentation locally.
Checklist

Add info about viewing compiled docs via www at NERSC

---

.gitmodules
conda/bootstrap.py
conda/shared.py

`alphaBetaLab` is needed to support WaveWatchIII mesh creation.  Since the original repo isn't in active development, we will use my fork for now.  This includes an improved list of dependencies and support for shapely 2.x, needed for compatibility with Compass.
`alphaBetaLab` will be installed from source since we cannot create a conda-forge package given that the original repo isn't in active development.
`alphaBetaLab` will only be installed if the `./conda/configure_compass_env.py` script is called with the `--with_alphabetalab` flag.
This feature will remain undocumented for now, but should be documented once WaveWatchIII mesh creation is added to Compass.
Checklist

Add optional support for `alphaBetaLab` package

---

conda/bootstrap.py

This merge switches to installing `cmake` and `cxx-compiler` in the deployment environment (not the final compass environment) and use them to build Jigsaw.  This prevents build tools from being left in the compass conda environment that later interfere with system tools and/or the spack environment.
This merge also removes a temporary fix from #757 on Anvil that is not needed after this "real" fix.
Checklist
closes #759

Fix jigsaw build

---

compass/landice/tests/antarctica/mesh.py
compass/landice/tests/greenland/mesh.py
compass/landice/tests/humboldt/mesh.py
compass/landice/tests/kangerlussuaq/mesh.py
compass/landice/tests/koge_bugt_s/mesh.py
compass/landice/tests/thwaites/mesh.py

Update file names on LCRC server to use files that do not have negative basal heat flux.
Note: The Antarctic data files still include NaNs as missing values. This requires the changes in https://github.com/MPAS-Dev/MPAS-Tools/pull/551 to pass.
Checklist

Update file names on LCRC server

---

compass/ocean/mesh/cull.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/hurricane/hurricane.cfg

If there are land-locked cells at calving fronts of ice shelves, they need to be added to the land-ice mask so sea-ice doesn't get trapped there.
This merge also gets the minimum latitude and number of sweeps used in finding land-locked cells from config options.
Checklist
closes #746

Fix land-locked cells at calving fronts

---

compass/ocean/tests/isomip_plus/isomip_plus_test.py

This is needed to allow 4 km ISOMIP+ tests.
Checklist

Make sure ny is even in ISOMIP+ test cases

---

compass/ocean/tests/global_ocean/files_for_e3sm/e3sm_to_cmip_maps.py

Compass was prepending `20` to the creation date but our creation dates already include the full 4-digit year.
Checklist

Fix incorrect creation dates for e3sm_to_cmip maps

---

compass/ocean/tests/global_ocean/files_for_e3sm/e3sm_to_cmip_maps.py
compass/ocean/tests/global_ocean/files_for_e3sm/scrip.py

E3SM v3 supports 8 new types of mapping files that we want to support for mapping from MPAS-Ocean and -Seaice meshes to CMIP6 grids.
This merge also copies MPAS-Ocean and -Seaice SCRIP files to `diagnostics/grids` in addition to `inputdata` so they area available for creating mapping files for diagnostics.
Checklist

Update `e3sm_to_cmip_maps` step to create E3SMv3 maps

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_tidal_mixing.py
docs/developers_guide/landice/api.rst
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst

This field is needed for any meshes that will run in the `TMIX` configuration described here:
https://github.com/E3SM-Ocean-Discussion/E3SM/pull/76
The field gets remapped from a dataset that @irenavankova has preprocessed from the CATS tidal model,
see https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-ocean/tidal_mixing/README.txt.
Checklist

Add `files_for_e3sm` step for remapping rms tidal velocity

---

compass/ocean/tests/isomip_plus/forward.py
compass/ocean/tests/isomip_plus/ssh_adjustment.py
compass/ocean/time.py

This merge adds an ocean framework module `time` with a function `get_time_interval_string()` that can be used to make a time string from a number of days or seconds (taking into account fractions of a second).  This is a back-port of https://github.com/E3SM-Project/polaris/pull/158/files#diff-25e5a0739b2dea91e8c71a47f173206923d2572571b9b84a98a01fa58db876cd
The `isomip_plus` test group has been updated to use this functionality so fractional time steps can be used.
Checklist

Allow decimal time steps in `isomip_plus`

---

compass/ocean/mesh/cull.py
compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/files_for_e3sm_step.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_mesh.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py
docs/users_guide/ocean/test_groups/global_ocean.rst

This merge adds the ability to reroute data melt fluxes remapped from the Adusumilli et al. (2020) dataset that were previously removed completely instead to the nearest sub-ice-shelf cell.
This requires first remapping to the base mesh, then rerouting, then culling land and masking land ice in the result.
In order to facilitate making DISMF datasets for existing meshes, the base mesh is also written out as part of `files_for_e3sm` and placed in `share/meshes/mpas/ocean`.
Checklist

Reroute missing fluxes in data ice-shelf melt fluxes (DISMF)

---

compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

Switch DISMF to Paolo et al. (2023) dataset

---

compass/landice/__init__.py
compass/landice/mesh.py
compass/landice/tests/mesh_modifications/__init__.py
compass/landice/tests/mesh_modifications/subdomain_extractor/__init__.py
compass/landice/tests/mesh_modifications/subdomain_extractor/extract_region.py
compass/landice/tests/mesh_modifications/subdomain_extractor/subdomain_extractor.cfg
docs/developers_guide/landice/api.rst
docs/developers_guide/landice/test_groups/index.rst
docs/developers_guide/landice/test_groups/mesh_modifications.rst
docs/users_guide/landice/test_groups/index.rst
docs/users_guide/landice/test_groups/mesh_modifications.rst

This merge adds a test case for a subdomain extractor.  It allows a regional domain to be quickly created from an existing whole-ice-sheet domain using a mask.  The regional mask can come from a region_mask MPAS netCDF file or a geojson file.  Optionally, ancillary files (e.g. forcing or parameter files) can be remapped at the same time.
Checklist

Create test for extracting a MALI subdomain from a larger domain

---

compass/landice/mesh.py
compass/landice/tests/antarctica/mesh.py
compass/landice/tests/antarctica/mesh_gen/mesh_gen.cfg
docs/developers_guide/landice/api.rst
docs/developers_guide/landice/framework.rst
docs/developers_guide/landice/test_groups/antarctica.rst
docs/users_guide/landice/test_groups/antarctica.rst

This PR adds automates interpolation of observational data from gridded datasets to Antarctic mesh within COMPASS. This takes care of the peculiarities of the current gridded compilation dataset (antarctica_8km_2020_10_20.nc), as well as using conservative remapping directly from the high-resolution BedMachineAntarctica and MeASUReS velocity datasets. There is a fairly heavy degree of pre-processing done to get the BedMachine and MeASUReS datasets ready to be used here. The pre-processing includes renaming variables, setting reasonable _FillValue and missing_value attributes, extrapolating fields to avoid interpolation ramps at ice margins, updating mask values, and raising the bed topography at Lake Vostok to ensure a flat ice surface. Those data files and processing scripts currently …

Updated data interpolation for Antarctica mesh generation case

---

compass/landice/mesh.py

__Description__: 
This PR adds `edge` region masks to the default options of the `make_region_masks` function within the mesh module of the landice framework. 
The addition of `edge` masks for regions is needed the by the recent addition of SGH quantities to regional stats analysis member in `MALI-Dev` (https://github.com/MALI-Dev/E3SM/pull/105). 
Originally, we planned on adding `vertex` masks aswell, to forestall future problems. But after some experimentation with the [antarctic/mesh_gen](https://mpas-dev.github.io/compass/latest/users_guide/landice/test_groups/antarctica.html) testcase, the additional masks slow down testcase execution considerably (~50%). As _very_ few variables are defined on vertices, we've opted to leave them out of the defaults for now. 
__Checklist__

Add edge masks to default arguments of `make_region_masks` landice framework function

---

compass/ocean/mesh/cull.py

Since critical land blockages can cause new cells to be landlocked, we need to remove landlocked cells only after we have added land blockages to the land mask.
This merge also fixes a small issue where the `latitude_threshold` parameter for widening critical passages is now supplied from the appropriate config option, whereas it had previously been hard coded by mistake.
Checklist

Fixes to landlocked cells when culling global meshes 

---

compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/streams.dismf

This got missed in the pull request (#778) that switched to Paolo et al. (2023) melt rates.
Checklist

Fix DISMF dataset name in global ocean forward runs

---

compass/ocean/tests/global_ocean/files_for_e3sm/remap_tidal_mixing.py

Since the tidal model used to produce the dataset only covers the Southern Ocean, there is not much value in having the reampped dataset for meshes without cavities.  If we want to make a more general mixing parameterization that uses tidal information, we would need to use data from a global tidal model for the input dataset in the future.
Checklist

Only make tidal mixing files for meshes with cavities

---

compass/ocean/tests/utility/__init__.py
compass/ocean/tests/utility/cull_restarts/__init__.py
compass/ocean/tests/utility/cull_restarts/cull.py
compass/ocean/tests/utility/cull_restarts/cull_restarts.cfg
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/utility.rst
docs/users_guide/ocean/test_groups/utility.rst

This needs a new version of MPAS-Tools (not yet released) with https://github.com/MPAS-Dev/MPAS-Tools/pull/557
Checklist

Add util for culling MPAS-Ocean and -Seaice restart files

---

compass/ocean/tests/utility/__init__.py
compass/ocean/tests/utility/combine_topo/__init__.py
compass/ocean/tests/utility/combine_topo/combine_topo.cfg
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/utility.rst
docs/users_guide/ocean/test_groups/utility.rst

This is nearly identical to the script used to produce the current bathymetry at:
https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-ocean/provenance/combine_bedmachine_v3_gebco_2023.py
The major difference is that this utility doesn't downsample the BedMachine dataset to at 1 km grid (instead remapping the 500 m dataset to a 1/80 degree lat-lon grid).
Checklist

Add a utility for combining GEBCO and BedMachine topo

---

compass/version.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/recipe/meta.yaml

This version of mache uses newer OpenMPI libraries for Intel, needed to prevent jobs from hanging during cancellation, blocking nodes.

Update to mache v1.22.0

---

compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/initial_state.py
compass/ocean/tests/global_ocean/init/namelist.init
compass/ocean/tests/global_ocean/mesh/arrm10to60/arrm10to60.cfg
compass/ocean/tests/global_ocean/mesh/arrm10to60/namelist.init
compass/ocean/tests/global_ocean/mesh/rrs6to18/rrs6to18.cfg
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

Previously, we specified the minimum thickness of the global ocean, which was set to 10 m.
This is not a good approach with different vertical coordinates.  If we want to use the same settings across various vertical coordinates, it is more useful to require a minimum number of levels.
This merge changes the global ocean `initial_state` step to use config options to set the number of vertical levels both in the open ocean and in ice-shelf cavities.  Relatedly, we also add a config option to set the minimum layer thickness in cavities.
This change will affect the vertical 3D vertical cooridinate in all meshes (hopefully for the better).
For meshes that use variants of the 80-layer vertical coordinate, we set the minimum number of layers that sets the column thickness to either 10 or 20 m. …

Add config options for min levels

---

compass/landice/tests/greenland/mesh.py
compass/landice/tests/greenland/mesh_gen/mesh_gen.cfg
docs/developers_guide/landice/test_groups/greenland.rst
docs/users_guide/landice/test_groups/antarctica.rst
docs/users_guide/landice/test_groups/greenland.rst

This merge adds conservative remapping of observational data sets (thickness, bed topography, velocity, and uncertainties) onto the Greenland Ice Sheet mesh, and handles some of the peculiarities of the other gridded datasets (unit conversions, sign conventions, etc).
Checklist

Add conservative remapping of observational datasets onto Greenland Ice Sheet mesh

---

compass/landice/tests/ismip6_run/ismip6_ais_proj2300/__init__.py
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/albany_input.yaml
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/create_slm_mapping_files.py
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/ismip6_ais_proj2300.cfg
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/ismip6_ais_proj2300_4km_chicoma.cfg
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/ismip6_ais_proj2300_4km_nersc.cfg
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/ismip6_ais_proj2300_8km_nersc.cfg
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/namelist.landice
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/namelist.sealevel.template
compass/landice/tests/ismip6_run/ismip6_ais_proj2300/set_up_experiment.py
docs/developers_guide/landice/test_groups/ismip6_run.rst
docs/users_guide/landice/test_groups/ismip6_run.rst

This PR adds to the `/landice/ismip6_run/ismip_ais_proj2300` testcase the option to setup coupled MALI-Sea Level Model simulations using the ismip6-Antarctica-2300 experimental protocol. 
With these changes, inclusion of the SLM can be activated through a test case cfg option.  This will set up required namelist and input settings, as well as the namelist.sealevel file used by SLM.  It will also set up an additional test case step that generates the required mapping files between MALI and SLM.  This must be run before any of the experiments are run.
This PR requires addition of Pyproj string `projections['ais-bedmap2-sphere'] = '+proj=stere +lat_ts=-71.0 +lat_0=-90 +lon_0=0.0 +k_0=1.0 +x_0=0.0 +y_0=0.0 +ellps=sphere'` in the MPAS-Tools script `set_lat_lon_fields_in_planar_grid.py` to set …

Add an option to setup coupled MALI-SLM runs in the ismip6 run testgroup

---

compass/landice/tests/ismip6_run/ismip6_ais_proj2300/namelist.sealevel.template

In current setup, ISMIP6-2300 historical simulation is performed for 15 years between 2000-2015 CE, and the projection simulations start from year 2015 until 2301. Previously, the sea-level model namelist was set such that the total length of simulation covered by the SLM is 285 years to cover years between 2015-2300, but since we've decided to run the coupled MALI-SLM model for the historical period as well, the simulation length option in the SLM naemlist needs to be corrected to cover the whole 300 years (2000-2300). This PR includes the change.

Set simulation length in the SLM namelist to 300 years 

---

docs/developers_guide/landice/test_groups/mesh_modifications.rst

This PR fixes the label for the landice mesh_modifications test group in the devevlopers guide so it does not conflict with the section in the users guide with the same name.
Checklist

Fix label for landice mesh_modifications test group in dev guide

---

compass/ocean/tests/global_ocean/dynamic_adjustment/__init__.py

We want to do this as a sanity check even if it is below the threshold that will raise an error.
Checklist

Print max. temperature during dynamic adjustment

---

compass/ocean/iceshelf.py

This PR has some clean up needed to make SSH adjustment in the `iceshelf` framework work for adjusting SSH instead of land-ice pressure.
This was pulled out of #813 because that work no longer uses the `iceshelf` framework.
Checklist

Clean up `iceshelf` framework

---

compass/ocean/plot.py

Add histograms of areaCell and dcEdge to init plots

---

compass/landice/mesh.py

This merge removes an unnecessary assertion about the value of `cull_distance`, since it is handled by other logic.

Fix bug in limiting cull distance

---

compass/landice/mesh.py
compass/landice/tests/antarctica/mesh.py
compass/landice/tests/greenland/mesh.py
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostic_masks.py
compass/version.py
conda/compass_env/spec-file.template

This merge adds ISMIP6 region masks to the Greenland mesh, which extend beyond ice edge and will be useful for regional stats. It also makes use of the `allTags` argument when calling `GeometricFeatures.read()` instead of looping over tags for greater flexibility.
Note: This requires geometric_features version 1.4.0, which is not yet in the latest version of compass.
Checklist

Add ISMIP6 Greenland region masks that extend beyond ice edge

---

compass/ocean/tests/global_ocean/mesh/rrs6to18/dynamic_adjustment.yaml
compass/ocean/tests/global_ocean/mesh/rrs6to18/namelist.init
compass/ocean/tests/global_ocean/mesh/rrs6to18/rrs6to18.cfg

Long name: RRSwISC6to18L80E3SMv3r5
This RRS (Rossby-radius scaled) mesh has:
* 6 km resolution near the poles
* 18 km resolution at the equator
Mesh, initial condition, dynamic adjustment and files for E3SM will be on Chrysalis at:
```
/lcrc/group/e3sm/ac.xylar/compass_1.3/chrysalis/e3smv3-meshes/rrswisc6to18e3r5
```
This mesh is similar to RRSwISC6to18E3r4 #754 but with #800 to fill in holes in the land-ice mask and with a minimum water-column thickness of 20 m.
Checklist

New Mesh: RRSwISC6to18E3r5

---

compass/version.py
conda/compass_env/spec-file.template

For now, we need to constrain `numpy < 2.0`.  Hopefully, we can update MPAS-Tools and compass to work with numpy >=2.0 in the near future.
Checklist

Constrain numpy < 2.0

---

compass/ocean/tests/utility/combine_topo/__init__.py
compass/ocean/tests/utility/combine_topo/combine_topo.cfg

This merge updates the utility that creates the merged BedMachine and GEBCO topography dataset to include bathymetry and ice topography under grounded ice as long as that ice below sea level.  This is done to make the topography used in simulations without MALI coupling more similar to simulations where the topography will come from MALI in the near future.  Since grounding lines will move, we do not wish to mask the topography to only the floating domain.
However, including topography above sea level is problematic.  It can result in both bathymetry and ice-draft values that are above sea level even in cells where a significant fraction of the cell is below sea level (e.g. when bathymetry is shallow in the portion of the cell that is below sea level but steep in the portion that is above …

Mask only topography above sea level when remapping BedMachine topo 

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py

Following https://github.com/MPAS-Dev/compass/pull/813, the initial state is the same whether ice shelf cavities are present or not.  It is the result of the `init/initial_state` step.
The `remap_ice_shelf_melt` step in `files_for_e3sm` needs to find the output in the corresponding `remap_ice_shelf_melt` in the `init` test case during `setup()` because that step no longer exists at construction.
Checklist

Fix files for E3SM following reorg of init

---

compass/landice/tests/calving_dt_convergence/dt_convergence_test/__init__.py
compass/landice/tests/eismint2/standard_experiments/visualize.py
compass/landice/tests/ensemble_generator/plot_ensemble.py
compass/ocean/tests/global_convergence/cosine_bell/analysis.py
compass/ocean/tests/sphere_transport/process_output.py
compass/ocean/tests/tides/analysis/__init__.py
compass/version.py
conda/compass_env/spec-file.template

Update to compass 1.4.0-alpha.4, numpy >=2.0, mpas_tools 0.34.1, matplotlib >=3.9.0

---

compass/ocean/tests/global_ocean/analysis_test/__init__.py
compass/ocean/tests/global_ocean/daily_output_test/__init__.py
compass/ocean/tests/global_ocean/decomp_test/__init__.py
compass/ocean/tests/global_ocean/dynamic_adjustment/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/write_coeffs_reconstruct/__init__.py
compass/ocean/tests/global_ocean/forward.py
compass/ocean/tests/global_ocean/monthly_output_test/__init__.py
compass/ocean/tests/global_ocean/performance_test/__init__.py
compass/ocean/tests/global_ocean/restart_test/__init__.py
compass/ocean/tests/global_ocean/threads_test/__init__.py

A lot of time is being taken to add metadata to output files during regression testing, even though that metadata will not be used by anyone and is not very useful.
We only want to be adding metadata to mesh files, initial conditions, outputs from dynamic adjustment and files staged for use as initial conditions in E3SM.
Checklist

Only add metadata to forward runs when useful

---

compass/ocean/mesh/cull.py

We need to address land-locked and land-ice-locked cells within the process for flood-filling to ensure that the land-ice mask is connected.  Otherwise, land-ice-locked cells added to the land-ice mask can create new regions of open ocean within the land ice.
Checklist

Fix land- and land-ice-locked cells

---

compass/ocean/mesh/cull.py

We need to do this before computing `landIceMask`.  Otherwise, critical passages cannot be used to open up channels of open ocean through areas covered by (grounded) land ice.
Checklist

Remove critical passages from `landIceFracObserved`

---

compass/ocean/mesh/cull.py

We need to set all land-ice related variables to zero in critical passages:
* `landIceFracObserved` (currently the case)
* `landIcePressureObserved`
* `landIceDraftObserved`
* `landIceGroundedFracObserved`
* `landIceFloatingFracObserved`
* `landIceThkObserved`
We also need to set `oceanFracObserved` to one.
Checklist

Set more topographic variables in critical passages

---

compass/ocean/mesh/cull.py

During the `cull_mesh` step of creating a global ocean mesh, if ice-shelf cavities are present, we need to flood fill to make sure all land ice is connected (no islands of isolated land ice). This merge changes the flood fill to be on all locations where `landIceFraction > 0`, not all locations where `landIceFraction > 0.5`. It then masks all `landIce*` fields to only be nonzero within the flood-filled region.  This prevents islands of nonzero `landIceFraction`, `landIcePressure`, `landIceDraft`, etc.
Checklist

Floodfill `landIceFraction`, not `landIceMask`

---

compass/landice/tests/mismipplus/setup_mesh.py

Per @trhille's experimenting, there are problems setting the Dirichlet BC's for resolutions $\leq$ 1000(m). This PR fixes #851 by using an absolute tolerance in all floating point comparisons of 5% of the appropriate cell spacing quantity.

Fix tolerance used for floating point comparison (Fixes #851) 

---

compass/ocean/mesh/cull.py
compass/ocean/mesh/remap_topography.py

Without this fix, meshes without cavities were ending up with a ring of depressed sea surface height around Antarctica.
Checklist

Set ssh to land-ice draft only in meshes with cavities

---

compass/ocean/mesh/remap_topography.cfg
compass/ocean/tests/utility/combine_topo/__init__.py
compass/ocean/tests/utility/combine_topo/combine_topo.cfg

Fix masking of ice draft and ice thickness in combine_topo

---

compass/ocean/mesh/remap_topography.cfg
compass/ocean/mesh/remap_topography.py
compass/ocean/tests/utility/combine_topo/__init__.py
compass/ocean/tests/utility/combine_topo/combine_topo.cfg

We don't want ice thickness and pressure to exceed their flotation
values.  Previously, we were only making sure that ice draft did
not exceed its flotation value (i.e. the draft was above the bed).
Checklist

Fix ice thickness and pressure where above flotation

---

.github/workflows/build_workflow.yml
.github/workflows/docs_workflow.yml

In this PR I made a few tweaks to the behavior of the CI workflows. These changes are:
1. `cancel_others` is now set to false by default, which should make it easier to decipher if a bug is isolated to a specific version of python via CI
2. The `defaults` channel has been removed as we can now exclusively use `conda-forge`
3. The timeout for the `pre-commit` job has been upped to 5 minutes

Tweak behaviors of CI workflows

---

compass/job/__init__.py
compass/job/job_script.template
compass/machines/chicoma-cpu.cfg
docs/developers_guide/machines/chicoma.rst
docs/users_guide/machines/chicoma.rst

This PR adds a `reservation` option to the `job` section of the config files, which is needed to run jobs in the `debug` queue on `chicoma`. 
While setting `qos=debug` used to work on `chicoma`, something switched in the last couple months and both `reservation` and `partition` need to set to `debug` for things to work. See the `chicoma` docs for reference: 
https://hpc.lanl.gov/policies/job-scheduling-policies.html#JobSchedulingPolicies-Chicoma
(Note: the entry in the table is for a interactive `debug` job, but the need to set both `reservation` and `partition` applies to batch jobs aswell). 
__Checklist__

Chicoma debug

---

conda/bootstrap.py
conda/configure_compass_env.py
docs/developers_guide/quick_start.rst

In this PR I added a few flags to the `python -m pip install [-e] .` command. The flags are:
* `-vv` indicates very verbose output. This flag is used during the CI runs to help with debugging.
* `--no-deps` indicates that pip should not install runtime dependencies from PyPi.
* `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.
I also had to make several formatting changes to existing code in order to satisfy the linter.
Checklist

Add additional flags to `pip install` command

---

compass/landice/mesh.py
compass/landice/tests/antarctica/mesh.py
compass/landice/tests/antarctica/mesh_gen/mesh_gen.cfg
compass/landice/tests/greenland/mesh.py
compass/landice/tests/greenland/mesh_gen/mesh_gen.cfg
docs/developers_guide/landice/api.rst
docs/developers_guide/landice/framework.rst
docs/users_guide/landice/test_groups/antarctica.rst
docs/users_guide/landice/test_groups/greenland.rst

With PRs #803 and #750 the `mesh_gen` testcases in the `greenland` and `antarctica` test groups now make better use of mesh generation utilities within the landice framework (e.g. `compass.landice.mesh`).   But there is still some redundant code as it relates to interpolation (e.g. `interp_ais_bedmachine` and `interp_ais_bedmachine` could be generalized to `interp_ais`). Continuing along that line, there is no real need to have separate interpolation functions for Antarctica (`interp_ais`) and Greenland (`interp_gis`). 
The purpose of the PR is generalize the existing interpolation functions to be applicable the standard datasets (i.e. measures and bedmachine) and standard icesheets (Antarctica and Greenland). With the generalized interpolation routine, the respective `mesh_gen` testcases …

Landice interpolation unification 

---

compass/ocean/mesh/low_res_topography.cfg
compass/ocean/tests/global_ocean/mesh/__init__.py

This is much less confusing than having them hard-coded deep inside of global ocean.
Checklist

Put low res topography options in a config file

---

compass/ocean/tests/global_ocean/files_for_e3sm/__init__.py
compass/ocean/tests/global_ocean/files_for_e3sm/add_total_iceberg_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/normalize_iceberg_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py

This is needed for an Antarctic balance approach in which all Antarctic solid runoff is converted into iceberg and ice-shelf melt with the patterns from the Merino et al. (2020) and Paolo et al. (2023) datasets.
Checklist

Add area integrated annual mean to data iceberg and ice-shelf flux files

---

compass/machines/pm-gpu.cfg
compass/version.py
conda/bootstrap.py
conda/compass_env/spec-file.template
conda/configure_compass_env.py
conda/default.cfg

- mache to v1.26.0 -- updates chicoma-cpu
- mpas_tools to v0.35.0
Checklist
MPAS-Ocean with `pr`:
MALI with `full_integration`:
MPAS-Ocean with `pr`:
MALI with `full_integration`:

Update to 1.6.0 alpha.1

---

compass/ocean/tests/isomip_plus/viz/plot.py

The shallow copy previously used (`copy.copy()`) was allowing modifications of attributes to persist across different plots, with unintended consequences.
Checklist
Fixes #877

Make a deep copy of `PatchCollection`s in ISOMIP+ test cases

---

compass/ocean/tests/utility/__init__.py
compass/ocean/tests/utility/combine_topo/__init__.py
compass/ocean/tests/utility/combine_topo/combine_topo.cfg
docs/developers_guide/ocean/test_groups/utility.rst
docs/users_guide/ocean/test_groups/utility.rst

The `ocean/utility/combine_topo` test has been split into two separate tests: one for a `lat_lon` target grid and one for a `cubed_sphere` target grid. The `cubed_sphere` test allows the migration to `mbtempest` for remapping bathymetry to MPAS grids by removing the pole singularities. The workflow for the existing `lat_lon` target grid has also been updated to use remapping tools more consistently between the GEBCO and BedMachineAntarctica data sets, and between the `lat_lon` and `cubed_sphere` target mesh workflows. Specifically, the GEBCO dataset is separated into tiles prior to remapping, `ESMF_RegridWeightGen` is used for building weights files, and `ncremap` is used for the final remapping step.
Checklist

Added `cubed_sphere` target grid test to `utility/combine_topo`

---

compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/utility/create_salin_restoring/__init__.py
compass/ocean/tests/utility/create_salin_restoring/combine.py
compass/ocean/tests/utility/create_salin_restoring/create_salin_restoring.cfg
compass/ocean/tests/utility/create_salin_restoring/extrap.py
compass/ocean/tests/utility/create_salin_restoring/remap.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/developers_guide/ocean/test_groups/utility.rst
docs/users_guide/ocean/test_groups/utility.rst

This requires a major reorganization of the step to be more like `remap_topography` after its recent reorganization.
Remapping is performed with `mbtempest`.  The public function `remap_sss()` has been removed.  (It was not mentioned in the docs.)
This merge also adds a remapping step to the utility that generates the SSS field from WOA23.  The data is remapped to a cubed-sphere grid at ne300 (~10 km) resolution.  Remapping from the cubed sphere to MPAS meshes will be *much* more performant than remapping from the WOA original lat-lon grid, particularly when there is smoothing near the poles as we do here.
The smoothing goes linearly from zero at 70 N to 1000 km at 90 N.
Checklist

Add smoothing to remapping of SSS restoring

---

.github/workflows/build_workflow.yml

We're seeing conflicts when CI runs and I'm hoping this will fix it.
This also turns off fast-fail in the CI matrix build.

In CI, use a unique cache directory for each python version

---

.github/workflows/build_workflow.yml
.github/workflows/docs_workflow.yml
.github/workflows/pre_commit_update_workflow.yml

This PR adds a few CI updates we've implemented in other repos recently:
1. I updated the default python version in various places to 3.13, and changed this version from a magic number to a variable in a few places (for consistency). 
2. I enabled `auto-update-conda` which we had disabled previously thinking it was causing trouble, but it wasn't.
3. I removed the caching step for creating a conda environment - it doesn't appear to be saving any time and we don't consider it worth keeping.
Checklist

CI updates and cleanup

---

compass/landice/mesh.py
compass/landice/tests/antarctica/mesh.py
compass/landice/tests/greenland/mesh.py

This PR passes the `parallel_executable` to a few functions that were hardcoded to use `srun`.  With the right input files, this allows testing on workstations with limited memory and cores.
Testing was done with subsampled GIS inputs (to 4km, thanks to @matthewhoffman) for the `landice/greenland/mesh_gen` test.
Checklist

support running landice/greenland/mesh_gen test case on workstations

---

compass/ocean/tests/global_ocean/__init__.py
compass/ocean/tests/global_ocean/init/__init__.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/mesh/remap_mali_topography/__init__.py
compass/ocean/tests/global_ocean/mesh/remap_mali_topography/ais_2to10km.cfg
compass/ocean/tests/global_ocean/mesh/remap_mali_topography/ais_4to20km.cfg
compass/ocean/tests/global_ocean/mesh/so12to30/so12to30.cfg
docs/conf.py
docs/developers_guide/ocean/api.rst
docs/developers_guide/ocean/test_groups/global_ocean.rst
docs/users_guide/ocean/test_groups/global_ocean.rst

Long name: SOwISC12to30kmL80E3SMv3r4
This version of the Southern Ocean Regionally Refined Mesh (SORRM) has resolution that is:
* 12 km resolution around Antarctica
* 30 km elsewhere
It is intended to be similar to the Icos30 mesh except in the Southern Ocean and around Antarctica.
This mesh differs from r3 in https://github.com/MPAS-Dev/compass/pull/807 in that:
* MALI topography as well as masks for land ice, floating ice and ocean get combined with BedMachine Antarctica/GEBCO.
Checklist

New Mesh: SOwISC12to30E3r4

---

.github/workflows/gis_coarse_meshgen.yml

This PR adds a github action workflow for running a coarse GIS meshgen case on a 'free' github hosted runner.  The run takes about 11 minutes.  It is only triggered when a PR, in any of its commits, changes either of the following files:
https://github.com/SCOREC/compass/blob/368a4a5b0d22344b53c08dbd2c8fbebf6b738032/.github/workflows/gis_coarse_meshgen.yml#L7-L8
```
- compass/landice/mesh.py
- compass/landice/tests/greenland/mesh.py
```
Testing was done here by pushing changes to `compass/landice/tests/mesh.py`.  Those changes were reverted, but the action log is available here: https://github.com/MPAS-Dev/compass/actions/runs/14233471393/job/39888454918
As noted below in the checklist, this test is currently downloading the GIS input data from a public RPI box directory.  Is there a …

github action for running a coarse gis meshgen test

---

compass/ocean/tests/global_ocean/files_for_e3sm/add_total_iceberg_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/diagnostic_masks.py
compass/ocean/tests/global_ocean/files_for_e3sm/files_for_e3sm_step.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_initial_condition.py
compass/ocean/tests/global_ocean/files_for_e3sm/ocean_mesh.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_iceberg_climatology.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_sea_surface_salinity_restoring.py
compass/ocean/tests/global_ocean/files_for_e3sm/remap_tidal_mixing.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_graph_partition.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_initial_condition.py
compass/ocean/tests/global_ocean/files_for_e3sm/seaice_mesh.py
compass/ocean/tests/global_ocean/global_ocean.cfg
compass/ocean/tests/global_ocean/init/remap_ice_shelf_melt.py
compass/ocean/tests/global_ocean/mesh/rrs6to18/rrs6to18.cfg

The RRSwISC6to18E3r5 mesh had mesh, initial condition and mask files that were in NetCDF4 format, not CDF5.  This PR aims to fix that.
We also have seen int64 fields in masks.  This should be fixed in https://github.com/MPAS-Dev/MPAS-Tools/pull/603, so this PR should introduce a new MPAS-Tools version that brings in that change as well.
For the MOC mask file in `inputdata`, this merge also adopts the naming convention from https://github.com/E3SM-Project/E3SM/pull/7165, e.g.:
```
RRSwISC6to18E3r5_mocBasinsAndTransects20210623mg.20250205.nc
```
Checklist

Fix CDF5 and int32 in `files_for_e3sm`

---

.github/workflows/build_workflow.yml
.github/workflows/docs_workflow.yml
conda/shared.py

This PR switches CI to use the `setup-micromamba` GitHub action instead of the `setup-miniconda` GitHub action, in an effort to fix CI crashes caused by the latest `miniconda` version. 
To do this, I needed to make a change to `conda.shared`, so that it did not reference the `CONDA_EXE` variable. Apparently miniconda sets this environment var, but micromamba does not. 
Checklist

Switch CI from miniconda to micromamba

---

compass/ocean/mesh/remap_topography.py
compass/ocean/tests/global_ocean/mesh/__init__.py
compass/ocean/tests/global_ocean/mesh/remap_mali_topography/__init__.py

This pull request introduces changes to improve the handling of symlinking for unsmoothed topography in the `compass` ocean modeling framework. The key updates include adding a new attribute to track symlink status, modifying the logic for determining when to symlink, and updating related test cases to reflect these changes.
* Added a new attribute `symlinked_to_unsmoothed` to the `RemapTopography` class to track whether symlinking to unsmoothed topography is performed. (`compass/ocean/mesh/remap_topography.py`) [[1]](diffhunk://#diff-c1f0744d83f56af79d59a66197a0889974a619b64c10cd6895e84cfe6bc20576R34-R37) [[2]](diffhunk://#diff-c1f0744d83f56af79d59a66197a0889974a619b64c10cd6895e84cfe6bc20576R76)
* Refactored the `_symlink_unsmoothed` method to set the `symlinked_to_unsmoothed` attribute …

Fix steps for remapping MALI topography to an MPAS-Ocean base mesh

---

.github/workflows/pre_commit_update_workflow.yml

This merge mainly switches to using a personal access token for assigning reviewers and setting labels.  It also adds the ability to run the workflow manually.  It includes a few other bits of clean-up.
Checklist

Update the pre-commit upate workflow

---

compass/landice/tests/ismip6_forcing/create_mapfile.py

Fix bug introduced by commit e51fcd1 that switched the variable names `ds` and `ds_out` in several places.
Checklist

Fix inadvertent mixup of variable names in build_mapping_file()
